-- ============================================================
-- 08_merchants_import.sql — import all 693 stores as vendor_profiles.
-- Additive + idempotent. psql compatible. Run AFTER run_all.sql.
--   * 630 stores with a domain (keyed on domain; linked to orders)
--   * 63 stores with NO domain in the CSV (domain left blank; keyed on name)
-- ============================================================
ALTER TABLE vendor_profiles ALTER COLUMN user_id DROP NOT NULL;
ALTER TABLE vendor_profiles ADD COLUMN IF NOT EXISTS domain text;
ALTER TABLE vendor_profiles ALTER COLUMN status SET DEFAULT 'approved';
CREATE UNIQUE INDEX IF NOT EXISTS idx_vendor_profiles_domain ON vendor_profiles(domain);

-- Stores WITH a domain — upsert on domain.
INSERT INTO vendor_profiles (legal_name, trade_name, domain, website_url, city, country, status) VALUES
  ('Toronto Peptides', 'Toronto Peptides', 'torontopeptides.ca', 'https://torontopeptides.ca', 'Toronto', 'Canada', 'approved'),
  ('Ottawa Peptides', 'Ottawa Peptides', 'ottawapeptides.com', 'https://ottawapeptides.com', 'Ottawa', 'Canada', 'approved'),
  ('Calgary Peptides', 'Calgary Peptides', 'calgarypeptides.ca', 'https://calgarypeptides.ca', 'Calgary', 'Canada', 'approved'),
  ('Laval Peptides', 'Laval Peptides', 'lavalpeptides.ca', 'https://lavalpeptides.ca', 'Laval', 'Canada', 'approved'),
  ('Vancouver Peptides', 'Vancouver Peptides', 'vancouverpeptides.ca', 'https://vancouverpeptides.ca', 'Vancouver', 'Canada', 'approved'),
  ('Surrey Peptides', 'Surrey Peptides', 'surreypeptides.com', 'https://surreypeptides.com', 'Surrey', 'Canada', 'approved'),
  ('Burnaby Peptides', 'Burnaby Peptides', 'burnabypeptides.ca', 'https://burnabypeptides.ca', 'Burnaby', 'Canada', 'approved'),
  ('Edmonton Peptides', 'Edmonton Peptides', 'edmontonpeptides.com', 'https://edmontonpeptides.com', 'Edmonton', 'Canada', 'approved'),
  ('Brandon Peptides', 'Brandon Peptides', 'brandonpeptides.ca', 'https://brandonpeptides.ca', 'Brandon', 'Canada', 'approved'),
  ('Winnipeg Peptides', 'Winnipeg Peptides', 'winnipegpeptides.ca', 'https://winnipegpeptides.ca', 'Winnipeg', 'Canada', 'approved'),
  ('Steinbach Peptides', 'Steinbach Peptides', 'steinbachpeptides.com', 'https://steinbachpeptides.com', 'Steinbach', 'Canada', 'approved'),
  ('Saskatoon Peptides', 'Saskatoon Peptides', 'saskatoonpeptides.ca', 'https://saskatoonpeptides.ca', 'Saskatoon', 'Canada', 'approved'),
  ('Los Angeles Peptides', 'Los Angeles Peptides', 'losangelespeptides.com', 'https://losangelespeptides.com', 'Los Angeles', 'United States', 'approved'),
  ('San Diego Peptides', 'San Diego Peptides', 'peptidesandiego.com', 'https://peptidesandiego.com', 'San Diego', 'United States', 'approved'),
  ('San Jose Peptides', 'San Jose Peptides', 'peptidesanjose.com', 'https://peptidesanjose.com', 'San Jose', 'United States', 'approved'),
  ('Houston Peptides', 'Houston Peptides', 'houstonpeps.com', 'https://houstonpeps.com', 'Houston', 'United States', 'approved'),
  ('Dallas Peptides', 'Dallas Peptides', 'peptidesdallas.com', 'https://peptidesdallas.com', 'Dallas', 'United States', 'approved'),
  ('Rochester Peptides', 'Rochester Peptides', 'rochesterpeptides.com', 'https://rochesterpeptides.com', 'Rochester', 'United States', 'approved'),
  ('Philadelphia Peptides', 'Philadelphia Peptides', 'philadelphiapeptides.com', 'https://philadelphiapeptides.com', 'Philadelphia', 'United States', 'approved'),
  ('Halifax Peptides', 'Halifax Peptides', 'halifaxpeptides.ca', 'https://halifaxpeptides.ca', 'Halifax', 'Canada', 'approved'),
  ('Moncton Peptides', 'Moncton Peptides', 'monctonpeptides.ca', 'https://monctonpeptides.ca', 'Moncton', 'Canada', 'approved'),
  ('Fredericton Peptides', 'Fredericton Peptides', 'frederictonpeptides.ca', 'https://frederictonpeptides.ca', 'Fredericton', 'Canada', 'approved'),
  ('Summerside Peptides', 'Summerside Peptides', 'summersidepeptides.ca', 'https://summersidepeptides.ca', 'Summerside', 'Canada', 'approved'),
  ('Stratford Peptides', 'Stratford Peptides', 'stratfordpeptides.ca', 'https://stratfordpeptides.ca', 'Stratford', 'Canada', 'approved'),
  ('Truro Peptides', 'Truro Peptides', 'truropeptides.ca', 'https://truropeptides.ca', 'Truro', 'Canada', 'approved'),
  ('St. John''s Peptides', 'St. John''s Peptides', 'stjohnspeptides.ca', 'https://stjohnspeptides.ca', 'St. John''s', 'Canada', 'approved'),
  ('Mount Pearl Peptides', 'Mount Pearl Peptides', 'mountpearlpeptides.ca', 'https://mountpearlpeptides.ca', 'Mount Pearl', 'Canada', 'approved'),
  ('Cleveland Peptides', 'Cleveland Peptides', 'clevelandpeptides.com', 'https://clevelandpeptides.com', 'Cleveland', 'United States', 'approved'),
  ('Charlotte Peptides', 'Charlotte Peptides', 'charlottepeptides.com', 'https://charlottepeptides.com', 'Charlotte', 'United States', 'approved'),
  ('Raleigh Peptides', 'Raleigh Peptides', 'raleighpeptides.com', 'https://raleighpeptides.com', 'Raleigh', 'United States', 'approved'),
  ('Detroit Peptides', 'Detroit Peptides', 'detroitpeptides.com', 'https://detroitpeptides.com', 'Detroit', 'United States', 'approved'),
  ('Jacksonville Peptides', 'Jacksonville Peptides', 'jacksonvillepeptide.com', 'https://jacksonvillepeptide.com', 'Jacksonville', 'United States', 'approved'),
  ('San Antonio Peptides', 'San Antonio Peptides', 'sanantoniopeptides.com', 'https://sanantoniopeptides.com', 'San Antonio', 'United States', 'approved'),
  ('Buffalo Peptides', 'Buffalo Peptides', 'buffalopeptides.com', 'https://buffalopeptides.com', 'Buffalo', 'United States', 'approved'),
  ('Aurora Peptides', 'Aurora Peptides', 'peptidesaurora.com', 'https://peptidesaurora.com', 'Aurora', 'Canada', 'approved'),
  ('Columbus Peptides', 'Columbus Peptides', 'columbuspeptides.com', 'https://columbuspeptides.com', 'Columbus', 'United States', 'approved'),
  ('Greensboro Peptides', 'Greensboro Peptides', 'greensboropeptides.com', 'https://greensboropeptides.com', 'Greensboro', 'United States', 'approved'),
  ('Princeton Peptides', 'Princeton Peptides', 'princetonpeptides.com', 'https://princetonpeptides.com', 'Princeton', 'United States', 'approved'),
  ('Warren Peptides', 'Warren Peptides', 'warrenpeptides.com', 'https://warrenpeptides.com', 'Warren', 'United States', 'approved'),
  ('Grand Rapids Peptides', 'Grand Rapids Peptides', 'grandrapidspeptides.com', 'https://grandrapidspeptides.com', 'Grand Rapids', 'United States', 'approved'),
  ('Chicago Peptides', 'Chicago Peptides', 'peptideschicago.com', 'https://peptideschicago.com', 'Chicago', 'United States', 'approved'),
  ('Phoenix Peptides', 'Phoenix Peptides', 'peptidesphoenix.com', 'https://peptidesphoenix.com', 'Phoenix', 'United States', 'approved'),
  ('San Francisco Peptides', 'San Francisco Peptides', 'sanfranciscopeptides.com', 'https://sanfranciscopeptides.com', 'San Francisco', 'United States', 'approved'),
  ('Seattle Peptides', 'Seattle Peptides', 'peptideseattle.com', 'https://peptideseattle.com', 'Seattle', 'United States', 'approved'),
  ('Denver Peptides', 'Denver Peptides', 'peptidesdenver.com', 'https://peptidesdenver.com', 'Denver', 'United States', 'approved'),
  ('Boston Peptides', 'Boston Peptides', 'peptidesboston.com', 'https://peptidesboston.com', 'Boston', 'United States', 'approved'),
  ('Miami Peptides', 'Miami Peptides', 'miamipeps.com', 'https://miamipeps.com', 'Miami', 'United States', 'approved'),
  ('Atlanta Peptides', 'Atlanta Peptides', 'atlantapeps.com', 'https://atlantapeps.com', 'Atlanta', 'United States', 'approved'),
  ('Portland Peptides', 'Portland Peptides', 'peptidesportland.com', 'https://peptidesportland.com', 'Portland', 'United States', 'approved'),
  ('Pittsburgh Peptides', 'Pittsburgh Peptides', 'pittsburghpeptides.com', 'https://pittsburghpeptides.com', 'Pittsburgh', 'United States', 'approved'),
  ('Minneapolis Peptides', 'Minneapolis Peptides', 'minneapolispeptides.com', 'https://minneapolispeptides.com', 'Minneapolis', 'United States', 'approved'),
  ('Nashville Peptides', 'Nashville Peptides', 'peptidesnashville.com', 'https://peptidesnashville.com', 'Nashville', 'United States', 'approved'),
  ('Oakland Peptides', 'Oakland Peptides', 'oaklandpeptides.com', 'https://oaklandpeptides.com', 'Oakland', 'United States', 'approved'),
  ('Riverside Peptides', 'Riverside Peptides', 'riversidepeptides.com', 'https://riversidepeptides.com', 'Riverside', 'United States', 'approved'),
  ('Sacramento Peptides', 'Sacramento Peptides', 'peptidesacramento.com', 'https://peptidesacramento.com', 'Sacramento', 'United States', 'approved'),
  ('Norfolk Peptides', 'Norfolk Peptides', 'norfolkpeptides.com', 'https://norfolkpeptides.com', 'Norfolk', 'United States', 'approved'),
  ('Birmingham Peptides', 'Birmingham Peptides', 'birminghampeptides.com', 'https://birminghampeptides.com', 'Birmingham', 'United States', 'approved'),
  ('Richmond Peptides', 'Richmond Peptides', 'richmondpeps.com', 'https://richmondpeps.com', 'Richmond', 'United States', 'approved'),
  ('New Orleans Peptides', 'New Orleans Peptides', 'neworleanspeps.com', 'https://neworleanspeps.com', 'New Orleans', 'United States', 'approved'),
  ('Hamilton Peptides', 'Hamilton Peptides', 'hamiltonpeptides.ca', 'https://hamiltonpeptides.ca', 'Hamilton', 'Canada', 'approved'),
  ('Oakville Peptides', 'Oakville Peptides', 'oakvillepeptides.ca', 'https://oakvillepeptides.ca', 'Oakville', 'Canada', 'approved'),
  ('Burlington Peptides', 'Burlington Peptides', 'burlingtonpeptides.ca', 'https://burlingtonpeptides.ca', 'Burlington', 'Canada', 'approved'),
  ('Brampton Peptides', 'Brampton Peptides', 'bramptonpeptides.ca', 'https://bramptonpeptides.ca', 'Brampton', 'Canada', 'approved'),
  ('Kitchener Peptides', 'Kitchener Peptides', 'kitchenerpeps.com', 'https://kitchenerpeps.com', 'Kitchener', 'Canada', 'approved'),
  ('Windsor Peptides', 'Windsor Peptides', 'windsorpeptides.ca', 'https://windsorpeptides.ca', 'Windsor', 'Canada', 'approved'),
  ('Kingston Peptides', 'Kingston Peptides', 'kingstonpeptides.ca', 'https://kingstonpeptides.ca', 'Kingston', 'Canada', 'approved'),
  ('Barrie Peptides', 'Barrie Peptides', 'barriepeptides.ca', 'https://barriepeptides.ca', 'Barrie', 'Canada', 'approved'),
  ('Oshawa Peptides', 'Oshawa Peptides', 'oshawapeptides.ca', 'https://oshawapeptides.ca', 'Oshawa', 'Canada', 'approved'),
  ('Whitby Peptides', 'Whitby Peptides', 'whitbypeps.com', 'https://whitbypeps.com', 'Whitby', 'Canada', 'approved'),
  ('Pickering Peptides', 'Pickering Peptides', 'pickeringpeps.com', 'https://pickeringpeps.com', 'Pickering', 'Canada', 'approved'),
  ('Ajax Peptides', 'Ajax Peptides', 'ajaxpeptides.ca', 'https://ajaxpeptides.ca', 'Ajax', 'Canada', 'approved'),
  ('Richmond Hill Peptides', 'Richmond Hill Peptides', 'richmondhillpeptides.ca', 'https://richmondhillpeptides.ca', 'Richmond Hill', 'Canada', 'approved'),
  ('Mississauga Peptides', 'Mississauga Peptides', 'mississaugapeps.ca', 'https://mississaugapeps.ca', 'Mississauga', 'Canada', 'approved'),
  ('Victoria Peptides', 'Victoria Peptides', 'victoriapeps.ca', 'https://victoriapeps.ca', 'Victoria', 'Canada', 'approved'),
  ('Waterloo Peptides', 'Waterloo Peptides', 'waterloopeps.ca', 'https://waterloopeps.ca', 'Waterloo', 'Canada', 'approved'),
  ('Markham Peptides', 'Markham Peptides', 'markhampeps.ca', 'https://markhampeps.ca', 'Markham', 'Canada', 'approved'),
  ('Vaughan Peptides', 'Vaughan Peptides', 'vaughanpeps.ca', 'https://vaughanpeps.ca', 'Vaughan', 'Canada', 'approved'),
  ('Lethbridge Peptides', 'Lethbridge Peptides', 'lethbridgepeps.com', 'https://lethbridgepeps.com', 'Lethbridge', 'Canada', 'approved'),
  ('Guelph Peptides', 'Guelph Peptides', 'guelphpeps.ca', 'https://guelphpeps.ca', 'Guelph', 'Canada', 'approved'),
  ('Scarborough Peptides', 'Scarborough Peptides', 'scarboroughpeptides.ca', 'https://scarboroughpeptides.ca', 'Scarborough', 'Canada', 'approved'),
  ('North York Peptides', 'North York Peptides', 'northyorkpeptides.ca', 'https://northyorkpeptides.ca', 'North York', 'Canada', 'approved'),
  ('Etobicoke Peptides', 'Etobicoke Peptides', 'etobicokepeptides.ca', 'https://etobicokepeptides.ca', 'Etobicoke', 'Canada', 'approved'),
  ('East York Peptides', 'East York Peptides', 'eastyorkpeptides.ca', 'https://eastyorkpeptides.ca', 'East York', 'Canada', 'approved'),
  ('York Peptides', 'York Peptides', 'yorkpeptides.ca', 'https://yorkpeptides.ca', 'York', 'Canada', 'approved'),
  ('Milton Peptides', 'Milton Peptides', 'miltonpeptides.ca', 'https://miltonpeptides.ca', 'Milton', 'Canada', 'approved'),
  ('Clarington Peptides', 'Clarington Peptides', 'claringtonpeptides.ca', 'https://claringtonpeptides.ca', 'Clarington', 'Canada', 'approved'),
  ('Newmarket Peptides', 'Newmarket Peptides', 'newmarketpeptides.ca', 'https://newmarketpeptides.ca', 'Newmarket', 'Canada', 'approved'),
  ('King Peptides', 'King Peptides', 'kingpeptides.ca', 'https://kingpeptides.ca', 'King', 'Canada', 'approved'),
  ('Georgina Peptides', 'Georgina Peptides', 'georginapeptides.ca', 'https://georginapeptides.ca', 'Georgina', 'Canada', 'approved'),
  ('East Gwillimbury Peptides', 'East Gwillimbury Peptides', 'eastgwillimburypeptides.ca', 'https://eastgwillimburypeptides.ca', 'East Gwillimbury', 'Canada', 'approved'),
  ('Caledon Peptides', 'Caledon Peptides', 'caledonpeptides.ca', 'https://caledonpeptides.ca', 'Caledon', 'Canada', 'approved'),
  ('Halton Hills Peptides', 'Halton Hills Peptides', 'haltonhillspeptides.ca', 'https://haltonhillspeptides.ca', 'Halton Hills', 'Canada', 'approved'),
  ('Orangeville Peptides', 'Orangeville Peptides', 'orangevillepeptides.ca', 'https://orangevillepeptides.ca', 'Orangeville', 'Canada', 'approved'),
  ('The Beaches Peptides', 'The Beaches Peptides', 'thebeachespeptides.ca', 'https://thebeachespeptides.ca', 'The Beaches', 'Canada', 'approved'),
  ('Liberty Village Peptide', 'Liberty Village Peptide', 'libertyvillagepeptides.ca', 'https://libertyvillagepeptides.ca', 'Liberty Village Peptide', 'Canada', 'approved'),
  ('Leslieville Peptides', 'Leslieville Peptides', 'leslievillepeptides.ca', 'https://leslievillepeptides.ca', 'Leslieville', 'Canada', 'approved'),
  ('Parkdale Peptides', 'Parkdale Peptides', 'parkdalepeptides.ca', 'https://parkdalepeptides.ca', 'Parkdale', 'Canada', 'approved'),
  ('Roncesvalles Peptides', 'Roncesvalles Peptides', 'roncesvallespeptides.ca', 'https://roncesvallespeptides.ca', 'Roncesvalles', 'Canada', 'approved'),
  ('The Annex Peptides', 'The Annex Peptides', 'theannexpeptides.ca', 'https://theannexpeptides.ca', 'The Annex', 'Canada', 'approved'),
  ('Danforth / Greektown Peptides', 'Danforth / Greektown Peptides', 'danforthpeptides.ca', 'https://danforthpeptides.ca', 'Danforth / Greektown', 'Canada', 'approved'),
  ('High Park Peptides', 'High Park Peptides', 'highparkpeptides.ca', 'https://highparkpeptides.ca', 'High Park', 'Canada', 'approved'),
  ('Mimico Peptides', 'Mimico Peptides', 'mimicopeptides.ca', 'https://mimicopeptides.ca', 'Mimico', 'Canada', 'approved'),
  ('Leaside Peptides', 'Leaside Peptides', 'leasidepeptides.ca', 'https://leasidepeptides.ca', 'Leaside', 'Canada', 'approved'),
  ('Don Mills Peptides', 'Don Mills Peptides', 'donmillspeptides.ca', 'https://donmillspeptides.ca', 'Don Mills', 'Canada', 'approved'),
  ('Willowdale Peptides', 'Willowdale Peptides', 'willowdalepeptides.ca', 'https://willowdalepeptides.ca', 'Willowdale', 'Canada', 'approved'),
  ('Thornhill Peptides', 'Thornhill Peptides', 'thornhillpeptides.ca', 'https://thornhillpeptides.ca', 'Thornhill', 'Canada', 'approved'),
  ('Unionville Peptides', 'Unionville Peptides', 'unionvillepeptides.ca', 'https://unionvillepeptides.ca', 'Unionville', 'Canada', 'approved'),
  ('Woodbridge Peptides', 'Woodbridge Peptides', 'woodbridgepeptides.ca', 'https://woodbridgepeptides.ca', 'Woodbridge', 'Canada', 'approved'),
  ('Maple Peptides', 'Maple Peptides', 'maplepeptides.ca', 'https://maplepeptides.ca', 'Maple', 'Canada', 'approved'),
  ('Concord Peptides', 'Concord Peptides', 'concordpeptides.ca', 'https://concordpeptides.ca', 'Concord', 'Canada', 'approved'),
  ('Port Credit Peptides', 'Port Credit Peptides', 'portcreditpeptides.ca', 'https://portcreditpeptides.ca', 'Port Credit', 'Canada', 'approved'),
  ('Streetsville Peptides', 'Streetsville Peptides', 'streetsvillepeptides.ca', 'https://streetsvillepeptides.ca', 'Streetsville', 'Canada', 'approved'),
  ('Meadowvale Peptides', 'Meadowvale Peptides', 'meadowvalepeptides.ca', 'https://meadowvalepeptides.ca', 'Meadowvale', 'Canada', 'approved'),
  ('Erin Mills Peptides', 'Erin Mills Peptides', 'erinmillspeptides.ca', 'https://erinmillspeptides.ca', 'Erin Mills', 'Canada', 'approved'),
  ('Clarkson Peptides', 'Clarkson Peptides', 'clarksonpeptides.ca', 'https://clarksonpeptides.ca', 'Clarkson', 'Canada', 'approved'),
  ('Cooksville Peptides', 'Cooksville Peptides', 'cooksvillepeptides.com', 'https://cooksvillepeptides.com', 'Cooksville', 'Canada', 'approved'),
  ('Malton Peptides', 'Malton Peptides', 'maltonpeptides.ca', 'https://maltonpeptides.ca', 'Malton', 'Canada', 'approved'),
  ('Bramalea Peptides', 'Bramalea Peptides', 'bramaleapeptides.ca', 'https://bramaleapeptides.ca', 'Bramalea', 'Canada', 'approved'),
  ('Heart Lake Peptides', 'Heart Lake Peptides', 'heartlakepeptides.ca', 'https://heartlakepeptides.ca', 'Heart Lake', 'Canada', 'approved'),
  ('Mount Pleasant Peptides', 'Mount Pleasant Peptides', 'mountpleasantpeptides.ca', 'https://mountpleasantpeptides.ca', 'Mount Pleasant', 'Canada', 'approved'),
  ('Westmount Peptides', 'Westmount Peptides', 'westmountpeptides.ca', 'https://westmountpeptides.ca', 'Westmount', 'Canada', 'approved'),
  ('Mont-Royal / TMR Peptides', 'Mont-Royal / TMR Peptides', 'montroyaltmrpeptides.ca', 'https://montroyaltmrpeptides.ca', 'Mont-Royal / TMR', 'Canada', 'approved'),
  ('Outremont Peptides', 'Outremont Peptides', 'outremontpeptides.ca', 'https://outremontpeptides.ca', 'Outremont', 'Canada', 'approved'),
  ('Notre-Dame-de-l''Île-Perrot Peptides', 'Notre-Dame-de-l''Île-Perrot Peptides', 'notre-dame-de-lile-perrotpeptides.ca', 'https://notre-dame-de-lile-perrotpeptides.ca', 'Notre-Dame-de-l''Île-Perrot', 'Canada', 'approved'),
  ('Côte-Saint-Luc Peptides', 'Côte-Saint-Luc Peptides', 'cotesaintlucpeptides.ca', 'https://cotesaintlucpeptides.ca', 'Côte-Saint-Luc', 'Canada', 'approved'),
  ('Pincourt Peptides', 'Pincourt Peptides', 'pincourtpeptides.ca', 'https://pincourtpeptides.ca', 'Pincourt', 'Canada', 'approved'),
  ('Dorval Peptides', 'Dorval Peptides', 'dorvalpeptides.ca', 'https://dorvalpeptides.ca', 'Dorval', 'Canada', 'approved'),
  ('Pointe-Claire Peptides', 'Pointe-Claire Peptides', 'pointeclairepeptides.ca', 'https://pointeclairepeptides.ca', 'Pointe-Claire', 'Canada', 'approved'),
  ('Kirkland Peptides', 'Kirkland Peptides', 'kirklandpeptides.ca', 'https://kirklandpeptides.ca', 'Kirkland', 'Canada', 'approved'),
  ('Beaconsfield Peptides', 'Beaconsfield Peptides', 'beaconsfieldpeptides.ca', 'https://beaconsfieldpeptides.ca', 'Beaconsfield', 'Canada', 'approved'),
  ('Saint-Lazare Peptides', 'Saint-Lazare Peptides', 'saint-lazarepeptides.ca', 'https://saint-lazarepeptides.ca', 'Saint-Lazare', 'Canada', 'approved'),
  ('Varennes Peptides', 'Varennes Peptides', 'varennespeptides.ca', 'https://varennespeptides.ca', 'Varennes', 'Canada', 'approved'),
  ('Sainte-Julie Peptides', 'Sainte-Julie Peptides', 'sainte-juliepeptides.ca', 'https://sainte-juliepeptides.ca', 'Sainte-Julie', 'Canada', 'approved'),
  ('Dollard-des-Ormeaux Peptides', 'Dollard-des-Ormeaux Peptides', 'dollard-des-ormeauxpeptides.ca', 'https://dollard-des-ormeauxpeptides.ca', 'Dollard-des-Ormeaux', 'Canada', 'approved'),
  ('Stouffville Peptides', 'Stouffville Peptides', 'stouffvillepeptides.ca', 'https://stouffvillepeptides.ca', 'Stouffville', 'Canada', 'approved'),
  ('Longueuil Peptides', 'Longueuil Peptides', 'longueuilpeptides.ca', 'https://longueuilpeptides.ca', 'Longueuil', 'Canada', 'approved'),
  ('Brossard Peptides', 'Brossard Peptides', 'brossardpeptides.ca', 'https://brossardpeptides.ca', 'Brossard', 'Canada', 'approved'),
  ('Saint-Lambert Peptides', 'Saint-Lambert Peptides', 'saint-lambertpeptides.ca', 'https://saint-lambertpeptides.ca', 'Saint-Lambert', 'Canada', 'approved'),
  ('Boucherville Peptides', 'Boucherville Peptides', 'bouchervillepeptides.ca', 'https://bouchervillepeptides.ca', 'Boucherville', 'Canada', 'approved'),
  ('Saint-Bruno-de-Montarville Peptides', 'Saint-Bruno-de-Montarville Peptides', 'saint-bruno-de-montarvillepeptides.ca', 'https://saint-bruno-de-montarvillepeptides.ca', 'Saint-Bruno-de-Montarville', 'Canada', 'approved'),
  ('Saint-Hubert Peptides', 'Saint-Hubert Peptides', 'sainthubertpeptides.ca', 'https://sainthubertpeptides.ca', 'Saint-Hubert', 'Canada', 'approved'),
  ('Greenfield Park Peptides', 'Greenfield Park Peptides', 'greenfieldparkpeptides.ca', 'https://greenfieldparkpeptides.ca', 'Greenfield Park', 'Canada', 'approved'),
  ('Chambly Peptides', 'Chambly Peptides', 'chamblypeptides.ca', 'https://chamblypeptides.ca', 'Chambly', 'Canada', 'approved'),
  ('Châteauguay Peptides', 'Châteauguay Peptides', 'chateauguaypeptides.ca', 'https://chateauguaypeptides.ca', 'Châteauguay', 'Canada', 'approved'),
  ('Candiac Peptides', 'Candiac Peptides', 'candiacpeptides.ca', 'https://candiacpeptides.ca', 'Candiac', 'Canada', 'approved'),
  ('La Prairie Peptides', 'La Prairie Peptides', 'laprairiepeptides.ca', 'https://laprairiepeptides.ca', 'La Prairie', 'Canada', 'approved'),
  ('Sainte-Catherine Peptides', 'Sainte-Catherine Peptides', 'saintecatherinepeptides.ca', 'https://saintecatherinepeptides.ca', 'Sainte-Catherine', 'Canada', 'approved'),
  ('Saint-Constant Peptides', 'Saint-Constant Peptides', 'saintconstantpeptides.ca', 'https://saintconstantpeptides.ca', 'Saint-Constant', 'Canada', 'approved'),
  ('Carignan Peptides', 'Carignan Peptides', 'carignanpeptides.ca', 'https://carignanpeptides.ca', 'Carignan', 'Canada', 'approved'),
  ('Terrebonne Peptides', 'Terrebonne Peptides', 'terrebonnepeptides.ca', 'https://terrebonnepeptides.ca', 'Terrebonne', 'Canada', 'approved'),
  ('Repentigny Peptides', 'Repentigny Peptides', 'repentignypeptides.ca', 'https://repentignypeptides.ca', 'Repentigny', 'Canada', 'approved'),
  ('Mascouche Peptides', 'Mascouche Peptides', 'mascouchepeptides.ca', 'https://mascouchepeptides.ca', 'Mascouche', 'Canada', 'approved'),
  ('L''Assomption Peptides', 'L''Assomption Peptides', 'lassomptionpeptides.ca', 'https://lassomptionpeptides.ca', 'L''Assomption', 'Canada', 'approved'),
  ('Blainville Peptides', 'Blainville Peptides', 'blainvillepeptides.ca', 'https://blainvillepeptides.ca', 'Blainville', 'Canada', 'approved'),
  ('Boisbriand Peptides', 'Boisbriand Peptides', 'boisbriandpeptides.ca', 'https://boisbriandpeptides.ca', 'Boisbriand', 'Canada', 'approved'),
  ('Rosemère Peptides', 'Rosemère Peptides', 'rosemerepeptides.ca', 'https://rosemerepeptides.ca', 'Rosemère', 'Canada', 'approved'),
  ('Lorraine Peptides', 'Lorraine Peptides', 'lorrainepeptides.ca', 'https://lorrainepeptides.ca', 'Lorraine', 'Canada', 'approved'),
  ('Sainte-Thérèse Peptides', 'Sainte-Thérèse Peptides', 'sainte-theresepeptides.ca', 'https://sainte-theresepeptides.ca', 'Sainte-Thérèse', 'Canada', 'approved'),
  ('Saint-Eustache Peptides', 'Saint-Eustache Peptides', 'saint-eustachepeptides.ca', 'https://saint-eustachepeptides.ca', 'Saint-Eustache', 'Canada', 'approved'),
  ('Deux-Montagnes Peptides', 'Deux-Montagnes Peptides', 'deux-montagnespeptides.ca', 'https://deux-montagnespeptides.ca', 'Deux-Montagnes', 'Canada', 'approved'),
  ('Sainte-Marthe-sur-le-Lac Peptides', 'Sainte-Marthe-sur-le-Lac Peptides', 'sainte-marthe-sur-le-lacpeptides.ca', 'https://sainte-marthe-sur-le-lacpeptides.ca', 'Sainte-Marthe-sur-le-Lac', 'Canada', 'approved'),
  ('Saint-Jérôme Peptides', 'Saint-Jérôme Peptides', 'saint-jeromepeptides.ca', 'https://saint-jeromepeptides.ca', 'Saint-Jérôme', 'Canada', 'approved'),
  ('Vaudreuil-Dorion Peptides', 'Vaudreuil-Dorion Peptides', 'vaudreuil-dorionpeptides.ca', 'https://vaudreuil-dorionpeptides.ca', 'Vaudreuil-Dorion', 'Canada', 'approved'),
  ('L''Île-Perrot Peptides', 'L''Île-Perrot Peptides', 'lile-perrotpeptides.ca', 'https://lile-perrotpeptides.ca', 'L''Île-Perrot', 'Canada', 'approved'),
  ('Mile End Peptides', 'Mile End Peptides', 'mile-endpeptides.ca', 'https://mile-endpeptides.ca', 'Mile End', 'Canada', 'approved'),
  ('Griffintown Peptides', 'Griffintown Peptides', 'griffintownpeptides.ca', 'https://griffintownpeptides.ca', 'Griffintown', 'Canada', 'approved'),
  ('Notre-Dame-de-Grâce Peptides', 'Notre-Dame-de-Grâce Peptides', 'ndg-notre-dame-de-gracepeptides.ca', 'https://ndg-notre-dame-de-gracepeptides.ca', 'Notre-Dame-de-Grâce', 'Canada', 'approved'),
  ('Verdun Peptides', 'Verdun Peptides', 'verdunpeptides.ca', 'https://verdunpeptides.ca', 'Verdun', 'Canada', 'approved'),
  ('LaSalle Peptides', 'LaSalle Peptides', 'lasallepeptides.ca', 'https://lasallepeptides.ca', 'LaSalle', 'Canada', 'approved'),
  ('Lachine Peptides', 'Lachine Peptides', 'lachinepeptides.ca', 'https://lachinepeptides.ca', 'Lachine', 'Canada', 'approved'),
  ('Saint-Laurent Peptides', 'Saint-Laurent Peptides', 'saint-laurentpeptides.ca', 'https://saint-laurentpeptides.ca', 'Saint-Laurent', 'Canada', 'approved'),
  ('Anjou Peptides', 'Anjou Peptides', 'anjoupeptides.ca', 'https://anjoupeptides.ca', 'Anjou', 'Canada', 'approved'),
  ('Ahuntsic-Cartierville Peptides', 'Ahuntsic-Cartierville Peptides', 'ahuntsicpeptides.ca', 'https://ahuntsicpeptides.ca', 'Ahuntsic-Cartierville', 'Canada', 'approved'),
  ('Mercier-Hochelaga-Maisonneuve Peptides', 'Mercier-Hochelaga-Maisonneuve Peptides', 'mercier-hochelaga-maisonneuve.ca', 'https://mercier-hochelaga-maisonneuve.ca', 'Mercier-Hochelaga-Maisonneuve', 'Canada', 'approved'),
  ('Rosemont-La Petite-Patrie Peptides', 'Rosemont-La Petite-Patrie Peptides', 'rosemontpeptides.ca', 'https://rosemontpeptides.ca', 'Rosemont-La Petite-Patrie', 'Canada', 'approved'),
  ('Villeray-Saint-Michel-Parc-Extension Peptides', 'Villeray-Saint-Michel-Parc-Extension Peptides', 'villeraypeptides.ca', 'https://villeraypeptides.ca', 'Villeray-Saint-Michel-Parc-Extension', 'Canada', 'approved'),
  ('Rivière-des-Prairies-Pointe-aux-Trembles Peptides', 'Rivière-des-Prairies-Pointe-aux-Trembles Peptides', 'rdppeptides.ca', 'https://rdppeptides.ca', 'Rivière-des-Prairies-Pointe-aux-Trembles', 'Canada', 'approved'),
  ('Pierrefonds-Roxboro Peptides', 'Pierrefonds-Roxboro Peptides', 'pierrefondspeptides.ca', 'https://pierrefondspeptides.ca', 'Pierrefonds-Roxboro', 'Canada', 'approved'),
  ('L''Île-Bizard-Sainte-Geneviève Peptides', 'L''Île-Bizard-Sainte-Geneviève Peptides', 'ilebizardpeptides.ca', 'https://ilebizardpeptides.ca', 'L''Île-Bizard-Sainte-Geneviève', 'Canada', 'approved'),
  ('Côte-des-Neiges Peptides', 'Côte-des-Neiges Peptides', 'cotedesneigespeptides.ca', 'https://cotedesneigespeptides.ca', 'Côte-des-Neiges', 'Canada', 'approved'),
  ('Snowdon Peptides', 'Snowdon Peptides', 'snowdonpeptides.ca', 'https://snowdonpeptides.ca', 'Snowdon', 'Canada', 'approved'),
  ('Saint-Henri Peptides', 'Saint-Henri Peptides', 'saint-henripeptides.ca', 'https://saint-henripeptides.ca', 'Saint-Henri', 'Canada', 'approved'),
  ('Pointe-Saint-Charles Peptides', 'Pointe-Saint-Charles Peptides', 'thepointepeptides.ca', 'https://thepointepeptides.ca', 'Pointe-Saint-Charles', 'Canada', 'approved'),
  ('Hochelaga Peptides', 'Hochelaga Peptides', 'hochelagapeptides.ca', 'https://hochelagapeptides.ca', 'Hochelaga', 'Canada', 'approved'),
  ('Coquitlam Peptides', 'Coquitlam Peptides', 'coquitlampeptides.ca', 'https://coquitlampeptides.ca', 'Coquitlam', 'Canada', 'approved'),
  ('Pitt Meadows Peptides', 'Pitt Meadows Peptides', 'pittmeadowspeptides.ca', 'https://pittmeadowspeptides.ca', 'Pitt Meadows', 'Canada', 'approved'),
  ('Cloverdale Peptides', 'Cloverdale Peptides', 'cloverdalepeptides.ca', 'https://cloverdalepeptides.ca', 'Cloverdale', 'Canada', 'approved'),
  ('Delta Peptides', 'Delta Peptides', 'deltapeptides.ca', 'https://deltapeptides.ca', 'Delta', 'Canada', 'approved'),
  ('Maple Ridge Peptides', 'Maple Ridge Peptides', 'mapleridgepeptides.ca', 'https://mapleridgepeptides.ca', 'Maple Ridge', 'Canada', 'approved'),
  ('New Westminster Peptides', 'New Westminster Peptides', 'newwestminsterpeptides.ca', 'https://newwestminsterpeptides.ca', 'New Westminster', 'Canada', 'approved'),
  ('Fleetwood Peptides', 'Fleetwood Peptides', 'fleetwoodpeptides.ca', 'https://fleetwoodpeptides.ca', 'Fleetwood', 'Canada', 'approved'),
  ('Guildford Peptides', 'Guildford Peptides', 'guildfordpeptides.ca', 'https://guildfordpeptides.ca', 'Guildford', 'Canada', 'approved'),
  ('West Vancouver Peptides', 'West Vancouver Peptides', 'westvancouverpeptides.ca', 'https://westvancouverpeptides.ca', 'West Vancouver', 'Canada', 'approved'),
  ('Port Moody Peptides', 'Port Moody Peptides', 'portmoodypeptides.ca', 'https://portmoodypeptides.ca', 'Port Moody', 'Canada', 'approved'),
  ('Tsawwassen Peptides', 'Tsawwassen Peptides', 'tsawwassenpeptides.ca', 'https://tsawwassenpeptides.ca', 'Tsawwassen', 'Canada', 'approved'),
  ('Newton Peptides', 'Newton Peptides', 'newtonpeptides.ca', 'https://newtonpeptides.ca', 'Newton', 'Canada', 'approved'),
  ('Whalley Peptides', 'Whalley Peptides', 'whalleypeptides.ca', 'https://whalleypeptides.ca', 'Whalley', 'Canada', 'approved'),
  ('Panorama Ridge Peptides', 'Panorama Ridge Peptides', 'panoramaridgepeptides.ca', 'https://panoramaridgepeptides.ca', 'Panorama Ridge', 'Canada', 'approved'),
  ('Steveston Peptides', 'Steveston Peptides', 'stevestonpeptides.ca', 'https://stevestonpeptides.ca', 'Steveston', 'Canada', 'approved'),
  ('Kitsilano Peptides', 'Kitsilano Peptides', 'kitsilanopeptides.ca', 'https://kitsilanopeptides.ca', 'Kitsilano', 'Canada', 'approved'),
  ('Kerrisdale Peptides', 'Kerrisdale Peptides', 'kerrisdalepeptides.ca', 'https://kerrisdalepeptides.ca', 'Kerrisdale', 'Canada', 'approved'),
  ('Dunbar Peptides', 'Dunbar Peptides', 'dunbarpeptides.ca', 'https://dunbarpeptides.ca', 'Dunbar', 'Canada', 'approved'),
  ('Point Grey Peptides', 'Point Grey Peptides', 'pointgreypeptides.ca', 'https://pointgreypeptides.ca', 'Point Grey', 'Canada', 'approved'),
  ('Yaletown Peptides', 'Yaletown Peptides', 'yaletownpeptides.ca', 'https://yaletownpeptides.ca', 'Yaletown', 'Canada', 'approved'),
  ('Commercial Drive Peptides', 'Commercial Drive Peptides', 'commercialdrivepeptides.ca', 'https://commercialdrivepeptides.ca', 'Commercial Drive', 'Canada', 'approved'),
  ('Metrotown Peptides', 'Metrotown Peptides', 'metrotownpeptides.ca', 'https://metrotownpeptides.ca', 'Metrotown', 'Canada', 'approved'),
  ('Brentwood Peptides', 'Brentwood Peptides', 'brentwoodpeptides.ca', 'https://brentwoodpeptides.ca', 'Brentwood', 'Canada', 'approved'),
  ('Lougheed Peptides', 'Lougheed Peptides', 'lougheedpeptides.ca', 'https://lougheedpeptides.ca', 'Lougheed', 'Canada', 'approved'),
  ('Edmonds Peptides', 'Edmonds Peptides', 'edmondspeptides.ca', 'https://edmondspeptides.ca', 'Edmonds', 'Canada', 'approved'),
  ('Burke Mountain Peptides', 'Burke Mountain Peptides', 'burkemountainpeptides.ca', 'https://burkemountainpeptides.ca', 'Burke Mountain', 'Canada', 'approved'),
  ('Willoughby Peptides', 'Willoughby Peptides', 'willoughbypeptides.ca', 'https://willoughbypeptides.ca', 'Willoughby', 'Canada', 'approved'),
  ('Walnut Grove Peptides', 'Walnut Grove Peptides', 'walnutgrovepeptides.ca', 'https://walnutgrovepeptides.ca', 'Walnut Grove', 'Canada', 'approved'),
  ('Aldergrove Peptides', 'Aldergrove Peptides', 'aldergrovepeptides.ca', 'https://aldergrovepeptides.ca', 'Aldergrove', 'Canada', 'approved'),
  ('Mission Peptides', 'Mission Peptides', 'missionpeptides.ca', 'https://missionpeptides.ca', 'Mission', 'Canada', 'approved'),
  ('Abbotsford Peptides', 'Abbotsford Peptides', 'abbotsfordpeptides.ca', 'https://abbotsfordpeptides.ca', 'Abbotsford', 'Canada', 'approved'),
  ('Chilliwack Peptides', 'Chilliwack Peptides', 'chilliwackpeptides.ca', 'https://chilliwackpeptides.ca', 'Chilliwack', 'Canada', 'approved'),
  ('Squamish Peptides', 'Squamish Peptides', 'squamishpeptides.ca', 'https://squamishpeptides.ca', 'Squamish', 'Canada', 'approved'),
  ('Whistler Peptides', 'Whistler Peptides', 'whistlerpeptides.ca', 'https://whistlerpeptides.ca', 'Whistler', 'Canada', 'approved'),
  ('Airdrie Peptides', 'Airdrie Peptides', 'airdriepeptides.ca', 'https://airdriepeptides.ca', 'Airdrie', 'Canada', 'approved'),
  ('Cochrane Peptides', 'Cochrane Peptides', 'cochranepeptides.ca', 'https://cochranepeptides.ca', 'Cochrane', 'Canada', 'approved'),
  ('Chestermere Peptides', 'Chestermere Peptides', 'chestermerepeptides.ca', 'https://chestermerepeptides.ca', 'Chestermere', 'Canada', 'approved'),
  ('Okotoks Peptides', 'Okotoks Peptides', 'okotokspeptides.ca', 'https://okotokspeptides.ca', 'Okotoks', 'Canada', 'approved'),
  ('Strathmore Peptides', 'Strathmore Peptides', 'strathmorepeptides.ca', 'https://strathmorepeptides.ca', 'Strathmore', 'Canada', 'approved'),
  ('Canmore Peptides', 'Canmore Peptides', 'canmorepeptides.ca', 'https://canmorepeptides.ca', 'Canmore', 'Canada', 'approved'),
  ('Beltline Peptides', 'Beltline Peptides', 'beltlinepeptides.ca', 'https://beltlinepeptides.ca', 'Beltline', 'Canada', 'approved'),
  ('Bowness Peptides', 'Bowness Peptides', 'bownesspeptides.ca', 'https://bownesspeptides.ca', 'Bowness', 'Canada', 'approved'),
  ('Rocky Ridge Peptides', 'Rocky Ridge Peptides', 'rockyridgepeptides.ca', 'https://rockyridgepeptides.ca', 'Rocky Ridge', 'Canada', 'approved'),
  ('Dalhousie Peptides', 'Dalhousie Peptides', 'dalhousiepeptides.ca', 'https://dalhousiepeptides.ca', 'Dalhousie', 'Canada', 'approved'),
  ('St. Albert Peptides', 'St. Albert Peptides', 'stalbertpeptides.ca', 'https://stalbertpeptides.ca', 'St. Albert', 'Canada', 'approved'),
  ('Sherwood Park Peptides', 'Sherwood Park Peptides', 'sherwoodparkpeptides.ca', 'https://sherwoodparkpeptides.ca', 'Sherwood Park', 'Canada', 'approved'),
  ('Spruce Grove Peptides', 'Spruce Grove Peptides', 'sprucegrovepeptides.ca', 'https://sprucegrovepeptides.ca', 'Spruce Grove', 'Canada', 'approved'),
  ('Leduc Peptides', 'Leduc Peptides', 'leducpeptides.ca', 'https://leducpeptides.ca', 'Leduc', 'Canada', 'approved'),
  ('Fort Saskatchewan Peptides', 'Fort Saskatchewan Peptides', 'fortsaskatchewanpeptides.ca', 'https://fortsaskatchewanpeptides.ca', 'Fort Saskatchewan', 'Canada', 'approved'),
  ('Beaumont Peptides', 'Beaumont Peptides', 'beaumontpeptides.ca', 'https://beaumontpeptides.ca', 'Beaumont', 'Canada', 'approved'),
  ('Stony Plain Peptides', 'Stony Plain Peptides', 'stonyplainpeptides.ca', 'https://stonyplainpeptides.ca', 'Stony Plain', 'Canada', 'approved'),
  ('Morinville Peptides', 'Morinville Peptides', 'morinvillepeptides.ca', 'https://morinvillepeptides.ca', 'Morinville', 'Canada', 'approved'),
  ('Oliver Peptides', 'Oliver Peptides', 'oliverpeptides.ca', 'https://oliverpeptides.ca', 'Oliver', 'Canada', 'approved'),
  ('Mill Woods Peptides', 'Mill Woods Peptides', 'millwoodspeptides.ca', 'https://millwoodspeptides.ca', 'Mill Woods', 'Canada', 'approved'),
  ('The Meadows Peptides', 'The Meadows Peptides', 'themeadowspeptides.ca', 'https://themeadowspeptides.ca', 'The Meadows', 'Canada', 'approved'),
  ('Windermere Peptides', 'Windermere Peptides', 'windermerepeptides.ca', 'https://windermerepeptides.ca', 'Windermere', 'Canada', 'approved'),
  ('Rutherford Peptides', 'Rutherford Peptides', 'rutherfordpeptides.ca', 'https://rutherfordpeptides.ca', 'Rutherford', 'Canada', 'approved'),
  ('Terwillegar Peptides', 'Terwillegar Peptides', 'terwillegarpeptides.ca', 'https://terwillegarpeptides.ca', 'Terwillegar', 'Canada', 'approved'),
  ('Riverbend Peptides', 'Riverbend Peptides', 'riverbendpeptides.ca', 'https://riverbendpeptides.ca', 'Riverbend', 'Canada', 'approved'),
  ('Clareview Peptides', 'Clareview Peptides', 'clareviewpeptides.ca', 'https://clareviewpeptides.ca', 'Clareview', 'Canada', 'approved'),
  ('Castledowns Peptides', 'Castledowns Peptides', 'castledownspeptides.ca', 'https://castledownspeptides.ca', 'Castledowns', 'Canada', 'approved'),
  ('Ellerslie Peptides', 'Ellerslie Peptides', 'ellersliepeptides.ca', 'https://ellersliepeptides.ca', 'Ellerslie', 'Canada', 'approved'),
  ('Heritage Valley Peptides', 'Heritage Valley Peptides', 'heritagevalleypeptides.ca', 'https://heritagevalleypeptides.ca', 'Heritage Valley', 'Canada', 'approved'),
  ('Gatineau Peptides', 'Gatineau Peptides', 'gatineaupeptides.ca', 'https://gatineaupeptides.ca', 'Gatineau', 'Canada', 'approved'),
  ('Kanata Peptides', 'Kanata Peptides', 'kanatapeptides.ca', 'https://kanatapeptides.ca', 'Kanata', 'Canada', 'approved'),
  ('Orleans Peptides', 'Orleans Peptides', 'orleanspeptides.ca', 'https://orleanspeptides.ca', 'Orleans', 'Canada', 'approved'),
  ('Nepean Peptides', 'Nepean Peptides', 'nepeanpeptides.ca', 'https://nepeanpeptides.ca', 'Nepean', 'Canada', 'approved'),
  ('Gloucester Peptides', 'Gloucester Peptides', 'gloucesterpeptides.ca', 'https://gloucesterpeptides.ca', 'Gloucester', 'Canada', 'approved'),
  ('Barrhaven Peptides', 'Barrhaven Peptides', 'barrhavenpeptides.ca', 'https://barrhavenpeptides.ca', 'Barrhaven', 'Canada', 'approved'),
  ('Stittsville Peptides', 'Stittsville Peptides', 'stittsvillepeptides.ca', 'https://stittsvillepeptides.ca', 'Stittsville', 'Canada', 'approved'),
  ('Riverside South Peptides', 'Riverside South Peptides', 'riversidesouthpeptides.ca', 'https://riversidesouthpeptides.ca', 'Riverside South', 'Canada', 'approved'),
  ('Vanier Peptides', 'Vanier Peptides', 'vanierpeptides.ca', 'https://vanierpeptides.ca', 'Vanier', 'Canada', 'approved'),
  ('The Glebe Peptides', 'The Glebe Peptides', 'theglebepeptides.ca', 'https://theglebepeptides.ca', 'The Glebe', 'Canada', 'approved'),
  ('Centretown Peptides', 'Centretown Peptides', 'centretownpeptides.ca', 'https://centretownpeptides.ca', 'Centretown', 'Canada', 'approved'),
  ('Alta Vista Peptides', 'Alta Vista Peptides', 'altavistapeptides.ca', 'https://altavistapeptides.ca', 'Alta Vista', 'Canada', 'approved'),
  ('Sandy Hill Peptides', 'Sandy Hill Peptides', 'sandyhillpeptides.ca', 'https://sandyhillpeptides.ca', 'Sandy Hill', 'Canada', 'approved'),
  ('Aylmer Peptides', 'Aylmer Peptides', 'aylmerpeptides.ca', 'https://aylmerpeptides.ca', 'Aylmer', 'Canada', 'approved'),
  ('Hull Peptides', 'Hull Peptides', 'hullpeptides.ca', 'https://hullpeptides.ca', 'Hull', 'Canada', 'approved'),
  ('Carleton Place Peptides', 'Carleton Place Peptides', 'carletonplacepeptides.ca', 'https://carletonplacepeptides.ca', 'Carleton Place', 'Canada', 'approved'),
  ('Rockland Peptides', 'Rockland Peptides', 'rocklandpeptides.ca', 'https://rocklandpeptides.ca', 'Rockland', 'Canada', 'approved'),
  ('Cumberland Peptides', 'Cumberland Peptides', 'cumberlandpeptides.ca', 'https://cumberlandpeptides.ca', 'Cumberland', 'Canada', 'approved'),
  ('Findlay Creek Peptides', 'Findlay Creek Peptides', 'findlaycreekpeptides.ca', 'https://findlaycreekpeptides.ca', 'Findlay Creek', 'Canada', 'approved'),
  ('Langley Peptides', 'Langley Peptides', 'langleypeptides.ca', 'https://langleypeptides.ca', 'Langley', 'Canada', 'approved'),
  ('Senneville Peptides', 'Senneville Peptides', 'sennevillepeptides.ca', 'https://sennevillepeptides.ca', 'Senneville', 'Canada', 'approved'),
  ('Laval-des-Rapides Peptides', 'Laval-des-Rapides Peptides', 'lavaldesrapidespeptides.ca', 'https://lavaldesrapidespeptides.ca', 'Laval-des-Rapides', 'Canada', 'approved'),
  ('Welland Peptides', 'Welland Peptides', 'wellandpeptides.ca', 'https://wellandpeptides.ca', 'Welland', 'Canada', 'approved'),
  ('North Shore Peptides', 'North Shore Peptides', 'northshorepeptides.ca', 'https://northshorepeptides.ca', 'North Shore', 'Canada', 'approved'),
  ('North Perth Peptides', 'North Perth Peptides', 'northperthpeptides.ca', 'https://northperthpeptides.ca', 'North Perth', 'Canada', 'approved'),
  ('Rockwood Peptides', 'Rockwood Peptides', 'rockwoodpeptides.ca', 'https://rockwoodpeptides.ca', 'Rockwood', 'Canada', 'approved'),
  ('Locke Street Peptides', 'Locke Street Peptides', 'lockestreetpeptides.ca', 'https://lockestreetpeptides.ca', 'Locke Street', 'Canada', 'approved'),
  ('Timberlea Peptides', 'Timberlea Peptides', 'timberleapeptides.ca', 'https://timberleapeptides.ca', 'Timberlea', 'Canada', 'approved'),
  ('Signal Hill Peptides', 'Signal Hill Peptides', 'signalhillpeptides.ca', 'https://signalhillpeptides.ca', 'Signal Hill', 'Canada', 'approved'),
  ('Tuscany Peptides', 'Tuscany Peptides', 'tuscanypeptides.ca', 'https://tuscanypeptides.ca', 'Tuscany', 'Canada', 'approved'),
  ('Cranston Peptides', 'Cranston Peptides', 'cranstonpeptides.ca', 'https://cranstonpeptides.ca', 'Cranston', 'Canada', 'approved'),
  ('McKenzie Towne Peptides', 'McKenzie Towne Peptides', 'mckenzietownepeptides.ca', 'https://mckenzietownepeptides.ca', 'McKenzie Towne', 'Canada', 'approved'),
  ('Auburn Bay Peptides', 'Auburn Bay Peptides', 'auburnbaypeptides.ca', 'https://auburnbaypeptides.ca', 'Auburn Bay', 'Canada', 'approved'),
  ('Nolan Hill Peptides', 'Nolan Hill Peptides', 'nolanhillpeptides.ca', 'https://nolanhillpeptides.ca', 'Nolan Hill', 'Canada', 'approved'),
  ('Evanston Peptides', 'Evanston Peptides', 'evanstonpeptides.ca', 'https://evanstonpeptides.ca', 'Evanston', 'Canada', 'approved'),
  ('Legacy Peptides', 'Legacy Peptides', 'legacypeptides.ca', 'https://legacypeptides.ca', 'Legacy', 'Canada', 'approved'),
  ('Juniper Ridge Peptides', 'Juniper Ridge Peptides', 'juniperridgepeptides.ca', 'https://juniperridgepeptides.ca', 'Juniper Ridge', 'Canada', 'approved'),
  ('East St. Paul Peptides', 'East St. Paul Peptides', 'eaststpaulpeptides.ca', 'https://eaststpaulpeptides.ca', 'East St. Paul', 'Canada', 'approved'),
  ('Selkirk Peptides', 'Selkirk Peptides', 'selkirkpeptides.ca', 'https://selkirkpeptides.ca', 'Selkirk', 'Canada', 'approved'),
  ('St. Boniface Peptides', 'St. Boniface Peptides', 'stbonifacepeptides.ca', 'https://stbonifacepeptides.ca', 'St. Boniface', 'Canada', 'approved'),
  ('River Heights Peptides', 'River Heights Peptides', 'riverheightspeptides.ca', 'https://riverheightspeptides.ca', 'River Heights', 'Canada', 'approved'),
  ('St. James Peptides', 'St. James Peptides', 'stjamespeptides.ca', 'https://stjamespeptides.ca', 'St. James', 'Canada', 'approved'),
  ('Fort Garry Peptides', 'Fort Garry Peptides', 'fortgarrypeptides.ca', 'https://fortgarrypeptides.ca', 'Fort Garry', 'Canada', 'approved'),
  ('Charleswood Peptides', 'Charleswood Peptides', 'charleswoodpeptides.ca', 'https://charleswoodpeptides.ca', 'Charleswood', 'Canada', 'approved'),
  ('St. Vital Peptides', 'St. Vital Peptides', 'stvitalpeptides.ca', 'https://stvitalpeptides.ca', 'St. Vital', 'Canada', 'approved'),
  ('Transcona Peptides', 'Transcona Peptides', 'transconapeptides.ca', 'https://transconapeptides.ca', 'Transcona', 'Canada', 'approved'),
  ('North Kildonan Peptides', 'North Kildonan Peptides', 'northkildonanpeptides.ca', 'https://northkildonanpeptides.ca', 'North Kildonan', 'Canada', 'approved'),
  ('Waverley Heights Peptides', 'Waverley Heights Peptides', 'waverleyheightspeptides.ca', 'https://waverleyheightspeptides.ca', 'Waverley Heights', 'Canada', 'approved'),
  ('Bridgwater Peptides', 'Bridgwater Peptides', 'bridgwaterpeptides.ca', 'https://bridgwaterpeptides.ca', 'Bridgwater', 'Canada', 'approved'),
  ('Lévis Peptides', 'Lévis Peptides', 'levispeptides.ca', 'https://levispeptides.ca', 'Lévis', 'Canada', 'approved'),
  ('Sainte-Foy Peptides', 'Sainte-Foy Peptides', 'saintefoypeptides.ca', 'https://saintefoypeptides.ca', 'Sainte-Foy', 'Canada', 'approved'),
  ('Beauport Peptides', 'Beauport Peptides', 'beauportpeptides.ca', 'https://beauportpeptides.ca', 'Beauport', 'Canada', 'approved'),
  ('Charlesbourg Peptides', 'Charlesbourg Peptides', 'charlesbourgpeptides.ca', 'https://charlesbourgpeptides.ca', 'Charlesbourg', 'Canada', 'approved'),
  ('Les Rivières Peptides', 'Les Rivières Peptides', 'lesrivierespeptides.ca', 'https://lesrivierespeptides.ca', 'Les Rivières', 'Canada', 'approved'),
  ('Val-Bélair Peptides', 'Val-Bélair Peptides', 'valbelairpeptides.ca', 'https://valbelairpeptides.ca', 'Val-Bélair', 'Canada', 'approved'),
  ('L''Ancienne-Lorette Peptides', 'L''Ancienne-Lorette Peptides', 'lanciennelorettepeptides.ca', 'https://lanciennelorettepeptides.ca', 'L''Ancienne-Lorette', 'Canada', 'approved'),
  ('Saint-Augustin-de-Desmaures Peptides', 'Saint-Augustin-de-Desmaures Peptides', 'saintaugustindedesmaurespeptides.ca', 'https://saintaugustindedesmaurespeptides.ca', 'Saint-Augustin-de-Desmaures', 'Canada', 'approved'),
  ('Saint-Nicolas Peptides', 'Saint-Nicolas Peptides', 'saint-nicolaspeptides.ca', 'https://saint-nicolaspeptides.ca', 'Saint-Nicolas', 'Canada', 'approved'),
  ('Sillery Peptides', 'Sillery Peptides', 'sillerypeptides.ca', 'https://sillerypeptides.ca', 'Sillery', 'Canada', 'approved'),
  ('Montcalm Peptides', 'Montcalm Peptides', 'montcalmpeptides.ca', 'https://montcalmpeptides.ca', 'Montcalm', 'Canada', 'approved'),
  ('Saint-Roch Peptides', 'Saint-Roch Peptides', 'saintrochpeptides.ca', 'https://saintrochpeptides.ca', 'Saint-Roch', 'Canada', 'approved'),
  ('Limoilou Peptides', 'Limoilou Peptides', 'limoiloupeptides.ca', 'https://limoiloupeptides.ca', 'Limoilou', 'Canada', 'approved'),
  ('Cap-Rouge Peptides', 'Cap-Rouge Peptides', 'caprougepeptides.ca', 'https://caprougepeptides.ca', 'Cap-Rouge', 'Canada', 'approved'),
  ('Saint-Raymond Peptides', 'Saint-Raymond Peptides', 'saintraymondpeptides.ca', 'https://saintraymondpeptides.ca', 'Saint-Raymond', 'Canada', 'approved'),
  ('Stoney Creek Peptides', 'Stoney Creek Peptides', 'stoneycreekpeptides.ca', 'https://stoneycreekpeptides.ca', 'Stoney Creek', 'Canada', 'approved'),
  ('Ancaster Peptides', 'Ancaster Peptides', 'ancasterpeptides.ca', 'https://ancasterpeptides.ca', 'Ancaster', 'Canada', 'approved'),
  ('Flamborough Peptides', 'Flamborough Peptides', 'flamboroughpeptides.ca', 'https://flamboroughpeptides.ca', 'Flamborough', 'Canada', 'approved'),
  ('Glanbrook Peptides', 'Glanbrook Peptides', 'glanbrookpeptides.ca', 'https://glanbrookpeptides.ca', 'Glanbrook', 'Canada', 'approved'),
  ('Waterdown Peptides', 'Waterdown Peptides', 'waterdownpeptides.ca', 'https://waterdownpeptides.ca', 'Waterdown', 'Canada', 'approved'),
  ('Grimsby Peptides', 'Grimsby Peptides', 'grimsbypeptides.ca', 'https://grimsbypeptides.ca', 'Grimsby', 'Canada', 'approved'),
  ('Caledonia Peptides', 'Caledonia Peptides', 'caledoniapeptides.ca', 'https://caledoniapeptides.ca', 'Caledonia', 'Canada', 'approved'),
  ('Westdale Peptides', 'Westdale Peptides', 'westdalepeptides.ca', 'https://westdalepeptides.ca', 'Westdale', 'Canada', 'approved'),
  ('Hamilton Mountain Peptides', 'Hamilton Mountain Peptides', 'hamiltonmountainpeptides.ca', 'https://hamiltonmountainpeptides.ca', 'Hamilton Mountain', 'Canada', 'approved'),
  ('Elmira Peptides', 'Elmira Peptides', 'elmirapeptides.ca', 'https://elmirapeptides.ca', 'Elmira', 'Canada', 'approved'),
  ('Preston Peptides', 'Preston Peptides', 'prestonpeptides.ca', 'https://prestonpeptides.ca', 'Preston', 'Canada', 'approved'),
  ('Hespeler Peptides', 'Hespeler Peptides', 'hespelerpeptides.ca', 'https://hespelerpeptides.ca', 'Hespeler', 'Canada', 'approved'),
  ('Central Saanich Peptides', 'Central Saanich Peptides', 'centralsaanichpeptides.ca', 'https://centralsaanichpeptides.ca', 'Central Saanich', 'Canada', 'approved'),
  ('North Saanich Peptides', 'North Saanich Peptides', 'northsaanichpeptides.ca', 'https://northsaanichpeptides.ca', 'North Saanich', 'Canada', 'approved'),
  ('James Bay Peptides', 'James Bay Peptides', 'jamesbaypeptides.ca', 'https://jamesbaypeptides.ca', 'James Bay', 'Canada', 'approved'),
  ('West Kelowna Peptides', 'West Kelowna Peptides', 'westkelownapeptides.ca', 'https://westkelownapeptides.ca', 'West Kelowna', 'Canada', 'approved'),
  ('Sidney Peptides', 'Sidney Peptides', 'sidneypeptides.ca', 'https://sidneypeptides.ca', 'Sidney', 'Canada', 'approved'),
  ('South Surrey Peptides', 'South Surrey Peptides', 'southsurreypeptides.ca', 'https://southsurreypeptides.ca', 'South Surrey', 'Canada', 'approved'),
  ('View Royal Peptides', 'View Royal Peptides', 'viewroyalpeptides.ca', 'https://viewroyalpeptides.ca', 'View Royal', 'Canada', 'approved'),
  ('Sullivan Peptides', 'Sullivan Peptides', 'sullivanpeptides.ca', 'https://sullivanpeptides.ca', 'Sullivan', 'Canada', 'approved'),
  ('Fraser Heights Peptides', 'Fraser Heights Peptides', 'fraserheightspeptides.ca', 'https://fraserheightspeptides.ca', 'Fraser Heights', 'Canada', 'approved'),
  ('Bear Creek Peptides', 'Bear Creek Peptides', 'bearcreekpeptides.ca', 'https://bearcreekpeptides.ca', 'Bear Creek', 'Canada', 'approved'),
  ('Chomedey Peptides', 'Chomedey Peptides', 'chomedeypeptides.ca', 'https://chomedeypeptides.ca', 'Chomedey', 'Canada', 'approved'),
  ('Sainte-Dorothée Peptides', 'Sainte-Dorothée Peptides', 'saintedorotheepeptides.ca', 'https://saintedorotheepeptides.ca', 'Sainte-Dorothée', 'Canada', 'approved'),
  ('Fabreville Peptides', 'Fabreville Peptides', 'fabrevillepeptides.ca', 'https://fabrevillepeptides.ca', 'Fabreville', 'Canada', 'approved'),
  ('Duvernay Peptides', 'Duvernay Peptides', 'duvernaypeptides.ca', 'https://duvernaypeptides.ca', 'Duvernay', 'Canada', 'approved'),
  ('Pont-Viau Peptides', 'Pont-Viau Peptides', 'pontviaupeptides.ca', 'https://pontviaupeptides.ca', 'Pont-Viau', 'Canada', 'approved'),
  ('Vimont Peptides', 'Vimont Peptides', 'vimontpeptides.ca', 'https://vimontpeptides.ca', 'Vimont', 'Canada', 'approved'),
  ('Auteuil Peptides', 'Auteuil Peptides', 'auteuilpeptides.ca', 'https://auteuilpeptides.ca', 'Auteuil', 'Canada', 'approved'),
  ('Saint-François Peptides', 'Saint-François Peptides', 'saintfrancoispeptides.ca', 'https://saintfrancoispeptides.ca', 'Saint-François', 'Canada', 'approved'),
  ('Sainte-Rose Peptides', 'Sainte-Rose Peptides', 'sainterosepeptides.ca', 'https://sainterosepeptides.ca', 'Sainte-Rose', 'Canada', 'approved'),
  ('St. Thomas Peptides', 'St. Thomas Peptides', 'stthomaspeptides.ca', 'https://stthomaspeptides.ca', 'St. Thomas', 'Canada', 'approved'),
  ('Strathroy Peptides', 'Strathroy Peptides', 'strathroypeptides.ca', 'https://strathroypeptides.ca', 'Strathroy', 'Canada', 'approved'),
  ('Woodstock Peptides', 'Woodstock Peptides', 'woodstockpeptides.ca', 'https://woodstockpeptides.ca', 'Woodstock', 'Canada', 'approved'),
  ('Ingersoll Peptides', 'Ingersoll Peptides', 'ingersollpeptides.ca', 'https://ingersollpeptides.ca', 'Ingersoll', 'Canada', 'approved'),
  ('Byron Peptides', 'Byron Peptides', 'byronpeptides.ca', 'https://byronpeptides.ca', 'Byron', 'Canada', 'approved'),
  ('Oak Bay Peptides', 'Oak Bay Peptides', 'oakbaypeptides.ca', 'https://oakbaypeptides.ca', 'Oak Bay', 'Canada', 'approved'),
  ('Old East Village Peptides', 'Old East Village Peptides', 'oldeastvillagepeptides.ca', 'https://oldeastvillagepeptides.ca', 'Old East Village', 'Canada', 'approved'),
  ('Lambeth Peptides', 'Lambeth Peptides', 'lambethpeptides.ca', 'https://lambethpeptides.ca', 'Lambeth', 'Canada', 'approved'),
  ('White Oaks Peptides', 'White Oaks Peptides', 'whiteoakspeptides.ca', 'https://whiteoakspeptides.ca', 'White Oaks', 'Canada', 'approved'),
  ('Masonville Peptides', 'Masonville Peptides', 'masonvillepeptides.ca', 'https://masonvillepeptides.ca', 'Masonville', 'Canada', 'approved'),
  ('Hyde Park Peptides', 'Hyde Park Peptides', 'hydeparkpeptides.ca', 'https://hydeparkpeptides.ca', 'Hyde Park', 'Canada', 'approved'),
  ('Dartmouth Peptides', 'Dartmouth Peptides', 'dartmouthpeptides.ca', 'https://dartmouthpeptides.ca', 'Dartmouth', 'Canada', 'approved'),
  ('Bedford Peptides', 'Bedford Peptides', 'bedfordpeptides.ca', 'https://bedfordpeptides.ca', 'Bedford', 'Canada', 'approved'),
  ('Eastern Passage Peptides', 'Eastern Passage Peptides', 'easternpassagepeptides.ca', 'https://easternpassagepeptides.ca', 'Eastern Passage', 'Canada', 'approved'),
  ('Sackville Peptides', 'Sackville Peptides', 'sackvillepeptides.ca', 'https://sackvillepeptides.ca', 'Sackville', 'Canada', 'approved'),
  ('Cole Harbour Peptides', 'Cole Harbour Peptides', 'coleharbourpeptides.ca', 'https://coleharbourpeptides.ca', 'Cole Harbour', 'Canada', 'approved'),
  ('Spryfield Peptides', 'Spryfield Peptides', 'spryfieldpeptides.ca', 'https://spryfieldpeptides.ca', 'Spryfield', 'Canada', 'approved'),
  ('Fairview Peptides', 'Fairview Peptides', 'fairviewpeptides.ca', 'https://fairviewpeptides.ca', 'Fairview', 'Canada', 'approved'),
  ('Hammonds Plains Peptides', 'Hammonds Plains Peptides', 'hammondsplainspeptides.ca', 'https://hammondsplainspeptides.ca', 'Hammonds Plains', 'Canada', 'approved'),
  ('North End Halifax Peptides', 'North End Halifax Peptides', 'northendhalifaxpeptides.ca', 'https://northendhalifaxpeptides.ca', 'North End Halifax', 'Canada', 'approved'),
  ('South End Halifax Peptides', 'South End Halifax Peptides', 'southendhalifaxpeptides.ca', 'https://southendhalifaxpeptides.ca', 'South End Halifax', 'Canada', 'approved'),
  ('Warman Peptides', 'Warman Peptides', 'warmanpeptides.ca', 'https://warmanpeptides.ca', 'Warman', 'Canada', 'approved'),
  ('Martensville Peptides', 'Martensville Peptides', 'martensvillepeptides.ca', 'https://martensvillepeptides.ca', 'Martensville', 'Canada', 'approved'),
  ('Stonebridge Peptides', 'Stonebridge Peptides', 'stonebridgepeptides.ca', 'https://stonebridgepeptides.ca', 'Stonebridge', 'Canada', 'approved'),
  ('Brighton Peptides', 'Brighton Peptides', 'brightonpeptides.ca', 'https://brightonpeptides.ca', 'Brighton', 'Canada', 'approved'),
  ('Harbour Landing Peptides', 'Harbour Landing Peptides', 'harbourlandingpeptides.ca', 'https://harbourlandingpeptides.ca', 'Harbour Landing', 'Canada', 'approved'),
  ('Saanich Peptides', 'Saanich Peptides', 'saanichpeptides.ca', 'https://saanichpeptides.ca', 'Saanich', 'Canada', 'approved'),
  ('Langford Peptides', 'Langford Peptides', 'langfordpeptides.ca', 'https://langfordpeptides.ca', 'Langford', 'Canada', 'approved'),
  ('Colwood Peptides', 'Colwood Peptides', 'colwoodpeptides.ca', 'https://colwoodpeptides.ca', 'Colwood', 'Canada', 'approved'),
  ('Esquimalt Peptides', 'Esquimalt Peptides', 'esquimaltpeptides.ca', 'https://esquimaltpeptides.ca', 'Esquimalt', 'Canada', 'approved'),
  ('Niagara Falls Peptides', 'Niagara Falls Peptides', 'niagarafallspeptides.ca', 'https://niagarafallspeptides.ca', 'Niagara Falls', 'Canada', 'approved'),
  ('Thorold Peptides', 'Thorold Peptides', 'thoroldpeptides.ca', 'https://thoroldpeptides.ca', 'Thorold', 'Canada', 'approved'),
  ('Fort Erie Peptides', 'Fort Erie Peptides', 'forteriepeptides.ca', 'https://forteriepeptides.ca', 'Fort Erie', 'Canada', 'approved'),
  ('Port Colborne Peptides', 'Port Colborne Peptides', 'portcolbornepeptides.ca', 'https://portcolbornepeptides.ca', 'Port Colborne', 'Canada', 'approved'),
  ('Lincoln Peptides', 'Lincoln Peptides', 'lincolnpeptides.ca', 'https://lincolnpeptides.ca', 'Lincoln', 'Canada', 'approved'),
  ('Pelham Peptides', 'Pelham Peptides', 'pelhampeptides.ca', 'https://pelhampeptides.ca', 'Pelham', 'Canada', 'approved'),
  ('Niagara-on-the-Lake Peptides', 'Niagara-on-the-Lake Peptides', 'niagaraonthelakepeptides.ca', 'https://niagaraonthelakepeptides.ca', 'Niagara-on-the-Lake', 'Canada', 'approved'),
  ('Beamsville Peptides', 'Beamsville Peptides', 'beamsvillepeptides.ca', 'https://beamsvillepeptides.ca', 'Beamsville', 'Canada', 'approved'),
  ('Innisfil Peptides', 'Innisfil Peptides', 'innisfilpeptides.ca', 'https://innisfilpeptides.ca', 'Innisfil', 'Canada', 'approved'),
  ('Oro-Medonte Peptides', 'Oro-Medonte Peptides', 'oromedontepeptides.ca', 'https://oromedontepeptides.ca', 'Oro-Medonte', 'Canada', 'approved'),
  ('Springwater Peptides', 'Springwater Peptides', 'springwaterpeptides.ca', 'https://springwaterpeptides.ca', 'Springwater', 'Canada', 'approved'),
  ('Essa Peptides', 'Essa Peptides', 'essapeptides.ca', 'https://essapeptides.ca', 'Essa', 'Canada', 'approved'),
  ('New Tecumseth Peptides', 'New Tecumseth Peptides', 'newtecumsethpeptides.ca', 'https://newtecumsethpeptides.ca', 'New Tecumseth', 'Canada', 'approved'),
  ('Collingwood Peptides', 'Collingwood Peptides', 'collingwoodpeptides.ca', 'https://collingwoodpeptides.ca', 'Collingwood', 'Canada', 'approved'),
  ('Wasaga Beach Peptides', 'Wasaga Beach Peptides', 'wasagabeachpeptides.ca', 'https://wasagabeachpeptides.ca', 'Wasaga Beach', 'Canada', 'approved'),
  ('Orillia Peptides', 'Orillia Peptides', 'orilliapeptides.ca', 'https://orilliapeptides.ca', 'Orillia', 'Canada', 'approved'),
  ('Midland Peptides', 'Midland Peptides', 'midlandpeptides.ca', 'https://midlandpeptides.ca', 'Midland', 'Canada', 'approved'),
  ('Penetanguishene Peptides', 'Penetanguishene Peptides', 'penetanguishenepeptides.ca', 'https://penetanguishenepeptides.ca', 'Penetanguishene', 'Canada', 'approved'),
  ('Alcona Peptides', 'Alcona Peptides', 'alconapeptides.ca', 'https://alconapeptides.ca', 'Alcona', 'Canada', 'approved'),
  ('Angus Peptides', 'Angus Peptides', 'anguspeptides.ca', 'https://anguspeptides.ca', 'Angus', 'Canada', 'approved'),
  ('Alliston Peptides', 'Alliston Peptides', 'allistonpeptides.ca', 'https://allistonpeptides.ca', 'Alliston', 'Canada', 'approved'),
  ('Dieppe Peptides', 'Dieppe Peptides', 'dieppepeptides.ca', 'https://dieppepeptides.ca', 'Dieppe', 'Canada', 'approved'),
  ('Riverview Peptides', 'Riverview Peptides', 'riverviewpeptides.ca', 'https://riverviewpeptides.ca', 'Riverview', 'Canada', 'approved'),
  ('Magog Peptides', 'Magog Peptides', 'magogpeptides.ca', 'https://magogpeptides.ca', 'Magog', 'Canada', 'approved'),
  ('Rock Forest Peptides', 'Rock Forest Peptides', 'rockforestpeptides.ca', 'https://rockforestpeptides.ca', 'Rock Forest', 'Canada', 'approved'),
  ('Fleurimont Peptides', 'Fleurimont Peptides', 'fleurimontpeptides.ca', 'https://fleurimontpeptides.ca', 'Fleurimont', 'Canada', 'approved'),
  ('Jacques-Cartier Peptides', 'Jacques-Cartier Peptides', 'jacquescartierpeptides.ca', 'https://jacquescartierpeptides.ca', 'Jacques-Cartier', 'Canada', 'approved'),
  ('Cap-de-la-Madeleine Peptides', 'Cap-de-la-Madeleine Peptides', 'capdelamadeleinepeptides.ca', 'https://capdelamadeleinepeptides.ca', 'Cap-de-la-Madeleine', 'Canada', 'approved'),
  ('Saint-Louis-de-France Peptides', 'Saint-Louis-de-France Peptides', 'saintlouisdefrancepeptides.ca', 'https://saintlouisdefrancepeptides.ca', 'Saint-Louis-de-France', 'Canada', 'approved'),
  ('Bécancour Peptides', 'Bécancour Peptides', 'becancourpeptides.ca', 'https://becancourpeptides.ca', 'Bécancour', 'Canada', 'approved'),
  ('Shawinigan Peptides', 'Shawinigan Peptides', 'shawiniganpeptides.ca', 'https://shawiniganpeptides.ca', 'Shawinigan', 'Canada', 'approved'),
  ('Grand-Mère Peptides', 'Grand-Mère Peptides', 'grandmerepeptides.ca', 'https://grandmerepeptides.ca', 'Grand-Mère', 'Canada', 'approved'),
  ('Amherstview Peptides', 'Amherstview Peptides', 'amherstviewpeptides.ca', 'https://amherstviewpeptides.ca', 'Amherstview', 'Canada', 'approved'),
  ('Fergus Peptides', 'Fergus Peptides', 'ferguspeptides.ca', 'https://ferguspeptides.ca', 'Fergus', 'Canada', 'approved'),
  ('South End Peptides', 'South End Peptides', 'southendpeptides.ca', 'https://southendpeptides.ca', 'South End', 'Canada', 'approved'),
  ('Port Arthur Peptides', 'Port Arthur Peptides', 'portarthurpeptides.ca', 'https://portarthurpeptides.ca', 'Port Arthur', 'Canada', 'approved'),
  ('Fort William Peptides', 'Fort William Peptides', 'fortwilliampeptides.ca', 'https://fortwilliampeptides.ca', 'Fort William', 'Canada', 'approved'),
  ('Lacombe Peptides', 'Lacombe Peptides', 'lacombepeptides.ca', 'https://lacombepeptides.ca', 'Lacombe', 'Canada', 'approved'),
  ('Blackfalds Peptides', 'Blackfalds Peptides', 'blackfaldspeptides.ca', 'https://blackfaldspeptides.ca', 'Blackfalds', 'Canada', 'approved'),
  ('Sylvan Lake Peptides', 'Sylvan Lake Peptides', 'sylvanlakepeptides.ca', 'https://sylvanlakepeptides.ca', 'Sylvan Lake', 'Canada', 'approved'),
  ('West Lethbridge Peptides', 'West Lethbridge Peptides', 'westlethbridgepeptides.ca', 'https://westlethbridgepeptides.ca', 'West Lethbridge', 'Canada', 'approved'),
  ('North Lethbridge Peptides', 'North Lethbridge Peptides', 'northlethbridgepeptides.ca', 'https://northlethbridgepeptides.ca', 'North Lethbridge', 'Canada', 'approved'),
  ('South Lethbridge Peptides', 'South Lethbridge Peptides', 'southlethbridgepeptides.ca', 'https://southlethbridgepeptides.ca', 'South Lethbridge', 'Canada', 'approved'),
  ('Brocklehurst Peptides', 'Brocklehurst Peptides', 'brocklehurstpeptides.ca', 'https://brocklehurstpeptides.ca', 'Brocklehurst', 'Canada', 'approved'),
  ('Aberdeen Peptides', 'Aberdeen Peptides', 'aberdeenpeptides.ca', 'https://aberdeenpeptides.ca', 'Aberdeen', 'Canada', 'approved'),
  ('Parksville Peptides', 'Parksville Peptides', 'parksvillepeptides.ca', 'https://parksvillepeptides.ca', 'Parksville', 'Canada', 'approved'),
  ('North Nanaimo Peptides', 'North Nanaimo Peptides', 'northnanaimopeptides.ca', 'https://northnanaimopeptides.ca', 'North Nanaimo', 'Canada', 'approved'),
  ('Harewood Peptides', 'Harewood Peptides', 'harewoodpeptides.ca', 'https://harewoodpeptides.ca', 'Harewood', 'Canada', 'approved'),
  ('Valley East Peptides', 'Valley East Peptides', 'valleyeastpeptides.ca', 'https://valleyeastpeptides.ca', 'Valley East', 'Canada', 'approved'),
  ('Rayside-Balfour Peptides', 'Rayside-Balfour Peptides', 'raysidebalfourpeptides.ca', 'https://raysidebalfourpeptides.ca', 'Rayside-Balfour', 'Canada', 'approved'),
  ('Nickel Centre Peptides', 'Nickel Centre Peptides', 'nickelcentrepeptides.ca', 'https://nickelcentrepeptides.ca', 'Nickel Centre', 'Canada', 'approved'),
  ('Walden Peptides', 'Walden Peptides', 'waldenpeptides.ca', 'https://waldenpeptides.ca', 'Walden', 'Canada', 'approved'),
  ('New Sudbury Peptides', 'New Sudbury Peptides', 'newsudburypeptides.ca', 'https://newsudburypeptides.ca', 'New Sudbury', 'Canada', 'approved'),
  ('Paris Peptides', 'Paris Peptides', 'parispeptides.ca', 'https://parispeptides.ca', 'Paris', 'Canada', 'approved'),
  ('West Brant Peptides', 'West Brant Peptides', 'westbrantpeptides.ca', 'https://westbrantpeptides.ca', 'West Brant', 'Canada', 'approved'),
  ('Clearbrook Peptides', 'Clearbrook Peptides', 'clearbrookpeptides.ca', 'https://clearbrookpeptides.ca', 'Clearbrook', 'Canada', 'approved'),
  ('Matsqui Peptides', 'Matsqui Peptides', 'matsquipeptides.ca', 'https://matsquipeptides.ca', 'Matsqui', 'Canada', 'approved'),
  ('Sydney Peptides', 'Sydney Peptides', 'sydneypeptides.ca', 'https://sydneypeptides.ca', 'Sydney', 'Canada', 'approved'),
  ('Glace Bay Peptides', 'Glace Bay Peptides', 'glacebaypeptides.ca', 'https://glacebaypeptides.ca', 'Glace Bay', 'Canada', 'approved'),
  ('Springfield Peptides', 'Springfield Peptides', 'springfieldpeptides.ca', 'https://springfieldpeptides.ca', 'Springfield', 'Canada', 'approved'),
  ('Charny Peptides', 'Charny Peptides', 'charnypeptides.ca', 'https://charnypeptides.ca', 'Charny', 'Canada', 'approved'),
  ('Cambridge Peptides', 'Cambridge Peptides', 'cambridgepeptides.ca', 'https://cambridgepeptides.ca', 'Cambridge', 'Canada', 'approved'),
  ('Galt Peptides', 'Galt Peptides', 'galtpeptides.ca', 'https://galtpeptides.ca', 'Galt', 'Canada', 'approved'),
  ('Panorama Hills Peptides', 'Panorama Hills Peptides', 'panoramahillspeptides.ca', 'https://panoramahillspeptides.ca', 'Panorama Hills', 'Canada', 'approved'),
  ('Country Hills Peptides', 'Country Hills Peptides', 'countryhillspeptides.com', 'https://countryhillspeptides.com', 'Country Hills', 'Canada', 'approved'),
  ('Paradise Peptides', 'Paradise Peptides', 'paradisepeptides.ca', 'https://paradisepeptides.ca', 'Paradise', 'Canada', 'approved'),
  ('Garden City Peptides', 'Garden City Peptides', 'gardencitypeptides.ca', 'https://gardencitypeptides.ca', 'Garden City', 'Canada', 'approved'),
  ('La Haute-Saint-Charles Peptides', 'La Haute-Saint-Charles Peptides', 'lahautesaintcharlespeptides.ca', 'https://lahautesaintcharlespeptides.ca', 'La Haute-Saint-Charles', 'Canada', 'approved'),
  ('Loretteville Peptides', 'Loretteville Peptides', 'lorettevillepeptides.ca', 'https://lorettevillepeptides.ca', 'Loretteville', 'Canada', 'approved'),
  ('Mirabel Peptides', 'Mirabel Peptides', 'mirabelpeptides.ca', 'https://mirabelpeptides.ca', 'Mirabel', 'Canada', 'approved'),
  ('Saint-Jean-sur-Richelieu Peptides', 'Saint-Jean-sur-Richelieu Peptides', 'saint-jean-sur-richelieupeptides.ca', 'https://saint-jean-sur-richelieupeptides.ca', 'Saint-Jean-sur-Richelieu', 'Canada', 'approved'),
  ('Plateau-Mont-Royal Peptides', 'Plateau-Mont-Royal Peptides', 'plateau-mont-royalpeptides.ca', 'https://plateau-mont-royalpeptides.ca', 'Plateau-Mont-Royal', 'Canada', 'approved'),
  ('Port Coquitlam Peptides', 'Port Coquitlam Peptides', 'portcoquitlampeptides.ca', 'https://portcoquitlampeptides.ca', 'Port Coquitlam', 'Canada', 'approved'),
  ('Ladner Peptides', 'Ladner Peptides', 'ladnerpeptides.ca', 'https://ladnerpeptides.ca', 'Ladner', 'Canada', 'approved'),
  ('East Hastings Peptides', 'East Hastings Peptides', 'easthastingsespeptides.ca', 'https://easthastingsespeptides.ca', 'East Hastings', 'Canada', 'approved'),
  ('Mahogany Peptides', 'Mahogany Peptides', 'mahoganypeptides.ca', 'https://mahoganypeptides.ca', 'Mahogany', 'Canada', 'approved'),
  ('Seton Peptides', 'Seton Peptides', 'setonpeptides.ca', 'https://setonpeptides.ca', 'Seton', 'Canada', 'approved'),
  ('Clayton Park Peptides', 'Clayton Park Peptides', 'claytonparkpeptides.ca', 'https://claytonparkpeptides.ca', 'Clayton Park', 'Canada', 'approved'),
  ('Strathcona County Peptides', 'Strathcona County Peptides', 'strathconacountypeptides.ca', 'https://strathconacountypeptides.ca', 'Strathcona County', 'Canada', 'approved'),
  ('Chatham Peptides', 'Chatham Peptides', 'chathampeptides.ca', 'https://chathampeptides.ca', 'Chatham', 'Canada', 'approved'),
  ('Georgetown Peptides', 'Georgetown Peptides', 'georgetownpeptides.ca', 'https://georgetownpeptides.ca', 'Georgetown', 'Canada', 'approved'),
  ('Lakeshore Peptides', 'Lakeshore Peptides', 'lakeshorepeptides.ca', 'https://lakeshorepeptides.ca', 'Lakeshore', 'Canada', 'approved'),
  ('Bradford Peptides', 'Bradford Peptides', 'bradfordpeptides.ca', 'https://bradfordpeptides.ca', 'Bradford', 'Canada', 'approved'),
  ('Whitehorse Peptides', 'Whitehorse Peptides', 'whitehorsepeptides.ca', 'https://whitehorsepeptides.ca', 'Whitehorse', 'Canada', 'approved'),
  ('Keswick Peptides', 'Keswick Peptides', 'keswickpeptides.ca', 'https://keswickpeptides.ca', 'Keswick', 'Canada', 'approved'),
  ('Bolton Peptides', 'Bolton Peptides', 'boltonpeptides.ca', 'https://boltonpeptides.ca', 'Bolton', 'Canada', 'approved'),
  ('Prince Edward County Peptides', 'Prince Edward County Peptides', 'princeedwardcountypeptides.ca', 'https://princeedwardcountypeptides.ca', 'Prince Edward County', 'Canada', 'approved'),
  ('Quispamsis Peptides', 'Quispamsis Peptides', 'quispamsispeptides.ca', 'https://quispamsispeptides.ca', 'Quispamsis', 'Canada', 'approved'),
  ('Hudson Peptides', 'Hudson Peptides', 'hudsonpeptides.ca', 'https://hudsonpeptides.ca', 'Hudson', 'Canada', 'approved'),
  ('Lindsay Peptides', 'Lindsay Peptides', 'lindsaypeptides.ca', 'https://lindsaypeptides.ca', 'Lindsay', 'Canada', 'approved'),
  ('Owen Sound Peptides', 'Owen Sound Peptides', 'owensoundpeptides.ca', 'https://owensoundpeptides.ca', 'Owen Sound', 'Canada', 'approved'),
  ('South Frontenac Peptides', 'South Frontenac Peptides', 'southfrontenacpeptides.ca', 'https://southfrontenacpeptides.ca', 'South Frontenac', 'Canada', 'approved'),
  ('Yellowknife Peptides', 'Yellowknife Peptides', 'yellowknifepeptides.ca', 'https://yellowknifepeptides.ca', 'Yellowknife', 'Canada', 'approved'),
  ('Huntsville Peptides', 'Huntsville Peptides', 'huntsvillepeptides.ca', 'https://huntsvillepeptides.ca', 'Huntsville', 'Canada', 'approved'),
  ('Les Coteaux Peptides', 'Les Coteaux Peptides', 'lescoteauxpeptides.ca', 'https://lescoteauxpeptides.ca', 'Les Coteaux', 'Canada', 'approved'),
  ('Saugeen Shores Peptides', 'Saugeen Shores Peptides', 'saugeenshorespeptides.ca', 'https://saugeenshorespeptides.ca', 'Saugeen Shores', 'Canada', 'approved'),
  ('Buckingham Peptides', 'Buckingham Peptides', 'buckinghampeptides.ca', 'https://buckinghampeptides.ca', 'Buckingham', 'Canada', 'approved'),
  ('Loyalist Peptides', 'Loyalist Peptides', 'loyalistpeptides.ca', 'https://loyalistpeptides.ca', 'Loyalist', 'Canada', 'approved'),
  ('Bracebridge Peptides', 'Bracebridge Peptides', 'bracebridgepeptides.ca', 'https://bracebridgepeptides.ca', 'Bracebridge', 'Canada', 'approved'),
  ('Hanover Peptides', 'Hanover Peptides', 'hanoverpeptides.ca', 'https://hanoverpeptides.ca', 'Hanover', 'Canada', 'approved'),
  ('Laurentides Peptides', 'Laurentides Peptides', 'laurentidespeptides.ca', 'https://laurentidespeptides.ca', 'Laurentides', 'Canada', 'approved'),
  ('Clearview Peptides', 'Clearview Peptides', 'clearviewpeptides.ca', 'https://clearviewpeptides.ca', 'Clearview', 'Canada', 'approved'),
  ('Comox Peptides', 'Comox Peptides', 'comoxpeptides.ca', 'https://comoxpeptides.ca', 'Comox', 'Canada', 'approved'),
  ('Gaspe Peptides', 'Gaspe Peptides', 'gaspepeptides.ca', 'https://gaspepeptides.ca', 'Gaspe', 'Canada', 'approved'),
  ('Dolbeau-Mistassini Peptides', 'Dolbeau-Mistassini Peptides', 'dolbeaumistassinipeptides.ca', 'https://dolbeaumistassinipeptides.ca', 'Dolbeau-Mistassini', 'Canada', 'approved'),
  ('West Grey Peptides', 'West Grey Peptides', 'westgreypeptides.ca', 'https://westgreypeptides.ca', 'West Grey', 'Canada', 'approved'),
  ('New Hamburg Peptides', 'New Hamburg Peptides', 'newhamburgpeptides.ca', 'https://newhamburgpeptides.ca', 'New Hamburg', 'Canada', 'approved'),
  ('Sainte-Marie Peptides', 'Sainte-Marie Peptides', 'saintemariepeptides.ca', 'https://saintemariepeptides.ca', 'Sainte-Marie', 'Canada', 'approved'),
  ('South Stormont Peptides', 'South Stormont Peptides', 'southstormontpeptides.ca', 'https://southstormontpeptides.ca', 'South Stormont', 'Canada', 'approved'),
  ('Brock Peptides', 'Brock Peptides', 'brockpeptides.ca', 'https://brockpeptides.ca', 'Brock', 'Canada', 'approved'),
  ('Severn Peptides', 'Severn Peptides', 'severnpeptides.ca', 'https://severnpeptides.ca', 'Severn', 'Canada', 'approved'),
  ('Mont-Laurier Peptides', 'Mont-Laurier Peptides', 'montlaurierpeptides.ca', 'https://montlaurierpeptides.ca', 'Mont-Laurier', 'Canada', 'approved'),
  ('Mississippi Mills Peptides', 'Mississippi Mills Peptides', '15ta7c-0r.myshopify.com', 'https://15ta7c-0r.myshopify.com', 'Mississippi Mills', 'Canada', 'approved'),
  ('Port-Alfred Peptides', 'Port-Alfred Peptides', 'portalfredpeptides.ca', 'https://portalfredpeptides.ca', 'Port-Alfred', 'Canada', 'approved'),
  ('Cowansville Peptides', 'Cowansville Peptides', 'cowansvillepeptides.ca', 'https://cowansvillepeptides.ca', 'Cowansville', 'Canada', 'approved'),
  ('Lachute Peptides', 'Lachute Peptides', 'lachutepeptides.ca', 'https://lachutepeptides.ca', 'Lachute', 'Canada', 'approved'),
  ('Gravenhurst Peptides', 'Gravenhurst Peptides', 'gravenhurstpeptides.ca', 'https://gravenhurstpeptides.ca', 'Gravenhurst', 'Canada', 'approved'),
  ('Meaford Peptides', 'Meaford Peptides', 'meafordpeptides.ca', 'https://meafordpeptides.ca', 'Meaford', 'Canada', 'approved'),
  ('Rothesay Peptides', 'Rothesay Peptides', 'rothesaypeptides.ca', 'https://rothesaypeptides.ca', 'Rothesay', 'Canada', 'approved'),
  ('Georgian Bluffs Peptides', 'Georgian Bluffs Peptides', 'georgianbluffspeptides.ca', 'https://georgianbluffspeptides.ca', 'Georgian Bluffs', 'Canada', 'approved'),
  ('Hawkesbury Peptides', 'Hawkesbury Peptides', 'hawkesburypeptides.ca', 'https://hawkesburypeptides.ca', 'Hawkesbury', 'Canada', 'approved'),
  ('Gander Peptides', 'Gander Peptides', 'ganderpeptides.ca', 'https://ganderpeptides.ca', 'Gander', 'Canada', 'approved'),
  ('Adjala-Tosorontio Peptides', 'Adjala-Tosorontio Peptides', 'adjalatosorontiopeptides.ca', 'https://adjalatosorontiopeptides.ca', 'Adjala-Tosorontio', 'Canada', 'approved'),
  ('Grey Highlands Peptides', 'Grey Highlands Peptides', 'greyhighlandspeptides.ca', 'https://greyhighlandspeptides.ca', 'Grey Highlands', 'Canada', 'approved'),
  ('Arnprior Peptides', 'Arnprior Peptides', 'arnpriorpeptides.ca', 'https://arnpriorpeptides.ca', 'Arnprior', 'Canada', 'approved'),
  ('Tay Peptides', 'Tay Peptides', 'taypeptides.ca', 'https://taypeptides.ca', 'Tay', 'Canada', 'approved'),
  ('Ladysmith Peptides', 'Ladysmith Peptides', 'ladysmithpeptides.ca', 'https://ladysmithpeptides.ca', 'Ladysmith', 'Canada', 'approved'),
  ('Hauterive Peptides', 'Hauterive Peptides', 'hauterivepeptides.ca', 'https://hauterivepeptides.ca', 'Hauterive', 'Canada', 'approved'),
  ('La Tuque Peptides', 'La Tuque Peptides', 'latuquepeptides.ca', 'https://latuquepeptides.ca', 'La Tuque', 'Canada', 'approved'),
  ('Binbrook Peptides', 'Binbrook Peptides', 'binbrookpeptides.ca', 'https://binbrookpeptides.ca', 'Binbrook', 'Canada', 'approved'),
  ('Ramara Peptides', 'Ramara Peptides', 'ramarapeptides.ca', 'https://ramarapeptides.ca', 'Ramara', 'Canada', 'approved'),
  ('Bridgewater Peptides', 'Bridgewater Peptides', 'bridgewaterpeptides.ca', 'https://bridgewaterpeptides.ca', 'Bridgewater', 'Canada', 'approved'),
  ('Oromocto Peptides', 'Oromocto Peptides', 'oromoctopeptides.ca', 'https://oromoctopeptides.ca', 'Oromocto', 'Canada', 'approved'),
  ('Yorkville Peptides', 'Yorkville Peptides', 'yorkvillepeptides.ca', 'https://yorkvillepeptides.ca', 'Yorkville', 'Canada', 'approved'),
  ('Niverville Peptides', 'Niverville Peptides', 'nivervillepeptides.ca', 'https://nivervillepeptides.ca', 'Niverville', 'Canada', 'approved'),
  ('Hampstead Peptides', 'Hampstead Peptides', 'hampsteadpeptides.ca', 'https://hampsteadpeptides.ca', 'Hampstead', 'Canada', 'approved'),
  ('Montreal West Peptides', 'Montreal West Peptides', 'montrealwestpeptides.ca', 'https://montrealwestpeptides.ca', 'Montreal West', 'Canada', 'approved'),
  ('Sainte-Anne-de-Bellevue Peptides', 'Sainte-Anne-de-Bellevue Peptides', 'sainteannepeptides.ca', 'https://sainteannepeptides.ca', 'Sainte-Anne-de-Bellevue', 'Canada', 'approved'),
  ('LeMoyne Peptides', 'LeMoyne Peptides', 'lemoynepeptides.ca', 'https://lemoynepeptides.ca', 'LeMoyne', 'Canada', 'approved'),
  ('Delson Peptides', 'Delson Peptides', 'delsonpeptides.ca', 'https://delsonpeptides.ca', 'Delson', 'Canada', 'approved'),
  ('Vieux-Montréal Peptides', 'Vieux-Montréal Peptides', 'oldmontrealpeptides.ca', 'https://oldmontrealpeptides.ca', 'Vieux-Montréal', 'Canada', 'approved'),
  ('Little Italy Peptides', 'Little Italy Peptides', 'littleitalypeptides.ca', 'https://littleitalypeptides.ca', 'Little Italy', 'Canada', 'approved'),
  ('North Vancouver Peptides', 'North Vancouver Peptides', 'northvancouverpeptides.ca', 'https://northvancouverpeptides.ca', 'North Vancouver', 'Canada', 'approved'),
  ('Shaughnessy Peptides', 'Shaughnessy Peptides', 'shaughnessypeptides.ca', 'https://shaughnessypeptides.ca', 'Shaughnessy', 'Canada', 'approved'),
  ('Gastown Peptides', 'Gastown Peptides', 'gastownpeptides.ca', 'https://gastownpeptides.ca', 'Gastown', 'Canada', 'approved'),
  ('Banff Peptides', 'Banff Peptides', 'banffpeptides.ca', 'https://banffpeptides.ca', 'Banff', 'Canada', 'approved'),
  ('Kensington Peptides', 'Kensington Peptides', 'kensingtonpeptides.ca', 'https://kensingtonpeptides.ca', 'Kensington', 'Canada', 'approved'),
  ('Corydon Peptides', 'Corydon Peptides', 'corydonpeptides.ca', 'https://corydonpeptides.ca', 'Corydon', 'Canada', 'approved'),
  ('Bridgeland Peptides', 'Bridgeland Peptides', 'bridgelandpeptides.ca', 'https://bridgelandpeptides.ca', 'Bridgeland', 'Canada', 'approved'),
  ('Marda Loop Peptides', 'Marda Loop Peptides', 'mardalooppeptides.ca', 'https://mardalooppeptides.ca', 'Marda Loop', 'Canada', 'approved'),
  ('Springbank Peptides', 'Springbank Peptides', 'springbankpeptides.ca', 'https://springbankpeptides.ca', 'Springbank', 'Canada', 'approved'),
  ('Bearspaw Peptides', 'Bearspaw Peptides', 'bearspawpeptides.ca', 'https://bearspawpeptides.ca', 'Bearspaw', 'Canada', 'approved'),
  ('Varsity Peptides', 'Varsity Peptides', 'varsitypeptides.ca', 'https://varsitypeptides.ca', 'Varsity', 'Canada', 'approved'),
  ('Devon Peptides', 'Devon Peptides', 'devonpeptides.ca', 'https://devonpeptides.ca', 'Devon', 'Canada', 'approved'),
  ('Garneau Peptides', 'Garneau Peptides', 'garneaupeptides.ca', 'https://garneaupeptides.ca', 'Garneau', 'Canada', 'approved'),
  ('Bonnie Doon Peptides', 'Bonnie Doon Peptides', 'bonniedoonpeptides.ca', 'https://bonniedoonpeptides.ca', 'Bonnie Doon', 'Canada', 'approved'),
  ('Jasper Place Peptides', 'Jasper Place Peptides', 'jasperplacepeptides.ca', 'https://jasperplacepeptides.ca', 'Jasper Place', 'Canada', 'approved'),
  ('Griesbach Peptides', 'Griesbach Peptides', 'griesbachpeptides.ca', 'https://griesbachpeptides.ca', 'Griesbach', 'Canada', 'approved'),
  ('Lewis Estates Peptides', 'Lewis Estates Peptides', 'lewisestatespeptides.ca', 'https://lewisestatespeptides.ca', 'Lewis Estates', 'Canada', 'approved'),
  ('Manotick Peptides', 'Manotick Peptides', 'manotickpeptides.ca', 'https://manotickpeptides.ca', 'Manotick', 'Canada', 'approved'),
  ('Westboro Peptides', 'Westboro Peptides', 'westboropeptides.ca', 'https://westboropeptides.ca', 'Westboro', 'Canada', 'approved'),
  ('Hintonburg Peptides', 'Hintonburg Peptides', 'hintonburgpeptides.ca', 'https://hintonburgpeptides.ca', 'Hintonburg', 'Canada', 'approved'),
  ('Old Ottawa South Peptides', 'Old Ottawa South Peptides', 'oldottawasouthpeptides.ca', 'https://oldottawasouthpeptides.ca', 'Old Ottawa South', 'Canada', 'approved'),
  ('Embrun Peptides', 'Embrun Peptides', 'embrunpeptides.ca', 'https://embrunpeptides.ca', 'Embrun', 'Canada', 'approved'),
  ('Kemptville Peptides', 'Kemptville Peptides', 'kemptvillepeptides.ca', 'https://kemptvillepeptides.ca', 'Kemptville', 'Canada', 'approved'),
  ('James Street North Peptides', 'James Street North Peptides', 'jamesstreetnorthpeptides.ca', 'https://jamesstreetnorthpeptides.ca', 'James Street North', 'Canada', 'approved'),
  ('Chelsea Peptides', 'Chelsea Peptides', 'chelseapeptides.ca', 'https://chelseapeptides.ca', 'Chelsea', 'Canada', 'approved'),
  ('Almonte Peptides', 'Almonte Peptides', 'almontepeptides.ca', 'https://almontepeptides.ca', 'Almonte', 'Canada', 'approved'),
  ('West St. Paul Peptides', 'West St. Paul Peptides', 'weststpaulpeptides.ca', 'https://weststpaulpeptides.ca', 'West St. Paul', 'Canada', 'approved'),
  ('Macdonald Peptides', 'Macdonald Peptides', 'macdonaldpeptides.ca', 'https://macdonaldpeptides.ca', 'Macdonald', 'Canada', 'approved'),
  ('Garson Peptides', 'Garson Peptides', 'garsonpeptides.ca', 'https://garsonpeptides.ca', 'Garson', 'Canada', 'approved'),
  ('Bridgeview Peptides', 'Bridgeview Peptides', 'bridgeviewpeptides.ca', 'https://bridgeviewpeptides.ca', 'Bridgeview', 'Canada', 'approved'),
  ('Wolseley Peptides', 'Wolseley Peptides', 'wolseleypeptides.ca', 'https://wolseleypeptides.ca', 'Wolseley', 'Canada', 'approved'),
  ('Sage Creek Peptides', 'Sage Creek Peptides', 'sagecreekpeptides.ca', 'https://sagecreekpeptides.ca', 'Sage Creek', 'Canada', 'approved'),
  ('Stoneham-et-Tewkesbury Peptides', 'Stoneham-et-Tewkesbury Peptides', 'stonehamettewkesburypeptides.ca', 'https://stonehamettewkesburypeptides.ca', 'Stoneham-et-Tewkesbury', 'Canada', 'approved'),
  ('Lac-Beauport Peptides', 'Lac-Beauport Peptides', 'lacbeauportpeptides.ca', 'https://lacbeauportpeptides.ca', 'Lac-Beauport', 'Canada', 'approved'),
  ('Boischatel Peptides', 'Boischatel Peptides', 'boischatelpeptides.ca', 'https://boischatelpeptides.ca', 'Boischatel', 'Canada', 'approved'),
  ('Old Quebec Peptides', 'Old Quebec Peptides', 'oldquebecpeptides.ca', 'https://oldquebecpeptides.ca', 'Old Quebec', 'Canada', 'approved'),
  ('Shannon Peptides', 'Shannon Peptides', 'shannonpeptides.ca', 'https://shannonpeptides.ca', 'Shannon', 'Canada', 'approved'),
  ('Winona Peptides', 'Winona Peptides', 'winonapeptides.ca', 'https://winonapeptides.ca', 'Winona', 'Canada', 'approved'),
  ('Smithville Peptides', 'Smithville Peptides', 'smithvillepeptides.ca', 'https://smithvillepeptides.ca', 'Smithville', 'Canada', 'approved'),
  ('Concession Street Peptides', 'Concession Street Peptides', 'concessionstreetpeptides.ca', 'https://concessionstreetpeptides.ca', 'Concession Street', 'Canada', 'approved'),
  ('Laval-Ouest Peptides', 'Laval-Ouest Peptides', 'lavalouestpeptides.ca', 'https://lavalouestpeptides.ca', 'Laval-Ouest', 'Canada', 'approved'),
  ('Ayr Peptides', 'Ayr Peptides', 'ayrpeptides.ca', 'https://ayrpeptides.ca', 'Ayr', 'Canada', 'approved'),
  ('Breslau Peptides', 'Breslau Peptides', 'breslaupeptides.ca', 'https://breslaupeptides.ca', 'Breslau', 'Canada', 'approved'),
  ('Uptown Waterloo Peptides', 'Uptown Waterloo Peptides', 'uptownwaterloopeptides.ca', 'https://uptownwaterloopeptides.ca', 'Uptown Waterloo', 'Canada', 'approved'),
  ('Downtown Kitchener Peptides', 'Downtown Kitchener Peptides', 'downtownkitchenerpeptides.ca', 'https://downtownkitchenerpeptides.ca', 'Downtown Kitchener', 'Canada', 'approved'),
  ('Old North Peptides', 'Old North Peptides', 'oldnorthpeptides.ca', 'https://oldnorthpeptides.ca', 'Old North', 'Canada', 'approved'),
  ('Wortley Village Peptides', 'Wortley Village Peptides', 'wortleyvillagepeptides.ca', 'https://wortleyvillagepeptides.ca', 'Wortley Village', 'Canada', 'approved'),
  ('Larry Uteck Peptides', 'Larry Uteck Peptides', 'larryuteckpeptides.ca', 'https://larryuteckpeptides.ca', 'Larry Uteck', 'Canada', 'approved'),
  ('Tantallon Peptides', 'Tantallon Peptides', 'tantallonpeptides.ca', 'https://tantallonpeptides.ca', 'Tantallon', 'Canada', 'approved'),
  ('Fall River Peptides', 'Fall River Peptides', 'fallriverpeptides.ca', 'https://fallriverpeptides.ca', 'Fall River', 'Canada', 'approved'),
  ('Enfield Peptides', 'Enfield Peptides', 'enfieldpeptides.ca', 'https://enfieldpeptides.ca', 'Enfield', 'Canada', 'approved'),
  ('Porters Lake Peptides', 'Porters Lake Peptides', 'porterslakepeptides.ca', 'https://porterslakepeptides.ca', 'Porters Lake', 'Canada', 'approved'),
  ('Downtown Dartmouth Peptides', 'Downtown Dartmouth Peptides', 'downtowndartmouthpeptides.ca', 'https://downtowndartmouthpeptides.ca', 'Downtown Dartmouth', 'Canada', 'approved'),
  ('Burnside Peptides', 'Burnside Peptides', 'burnsidepeptides.ca', 'https://burnsidepeptides.ca', 'Burnside', 'Canada', 'approved'),
  ('Evergreen Peptides', 'Evergreen Peptides', 'evergreenpeptides.ca', 'https://evergreenpeptides.ca', 'Evergreen', 'Canada', 'approved'),
  ('Willowgrove Peptides', 'Willowgrove Peptides', 'willowgrovepeptides.ca', 'https://willowgrovepeptides.ca', 'Willowgrove', 'Canada', 'approved'),
  ('Nutana Peptides', 'Nutana Peptides', 'nutanapeptides.ca', 'https://nutanapeptides.ca', 'Nutana', 'Canada', 'approved'),
  ('Sutherland Peptides', 'Sutherland Peptides', 'sutherlandpeptides.ca', 'https://sutherlandpeptides.ca', 'Sutherland', 'Canada', 'approved'),
  ('Lawson Heights Peptides', 'Lawson Heights Peptides', 'lawsonheightspeptides.ca', 'https://lawsonheightspeptides.ca', 'Lawson Heights', 'Canada', 'approved'),
  ('Rosewood Peptides', 'Rosewood Peptides', 'rosewoodpeptides.ca', 'https://rosewoodpeptides.ca', 'Rosewood', 'Canada', 'approved'),
  ('Hanmer Peptides', 'Hanmer Peptides', 'hanmerpeptides.ca', 'https://hanmerpeptides.ca', 'Hanmer', 'Canada', 'approved'),
  ('Aspen Ridge Peptides', 'Aspen Ridge Peptides', 'aspenridgepeptides.ca', 'https://aspenridgepeptides.ca', 'Aspen Ridge', 'Canada', 'approved'),
  ('Silverspring Peptides', 'Silverspring Peptides', 'silverspringpeptides.ca', 'https://silverspringpeptides.ca', 'Silverspring', 'Canada', 'approved'),
  ('The Creeks Peptides', 'The Creeks Peptides', 'thecreekspeptides.ca', 'https://thecreekspeptides.ca', 'The Creeks', 'Canada', 'approved'),
  ('Cathedral Peptides', 'Cathedral Peptides', 'cathedralpeptides.ca', 'https://cathedralpeptides.ca', 'Cathedral', 'Canada', 'approved'),
  ('Hillsdale Peptides', 'Hillsdale Peptides', 'hillsdalepeptides.ca', 'https://hillsdalepeptides.ca', 'Hillsdale', 'Canada', 'approved'),
  ('Rochdale Peptides', 'Rochdale Peptides', 'rochdalepeptides.ca', 'https://rochdalepeptides.ca', 'Rochdale', 'Canada', 'approved'),
  ('Metchosin Peptides', 'Metchosin Peptides', 'metchosinpeptides.ca', 'https://metchosinpeptides.ca', 'Metchosin', 'Canada', 'approved'),
  ('Brentwood Bay Peptides', 'Brentwood Bay Peptides', 'brentwoodbaypeptides.ca', 'https://brentwoodbaypeptides.ca', 'Brentwood Bay', 'Canada', 'approved'),
  ('Cordova Bay Peptides', 'Cordova Bay Peptides', 'cordovabaypeptides.ca', 'https://cordovabaypeptides.ca', 'Cordova Bay', 'Canada', 'approved'),
  ('Fernwood Peptides', 'Fernwood Peptides', 'fernwoodpeptides.ca', 'https://fernwoodpeptides.ca', 'Fernwood', 'Canada', 'approved'),
  ('Fairfield Peptides', 'Fairfield Peptides', 'fairfieldpeptides.ca', 'https://fairfieldpeptides.ca', 'Fairfield', 'Canada', 'approved'),
  ('Tillicum Peptides', 'Tillicum Peptides', 'tillicumpeptides.ca', 'https://tillicumpeptides.ca', 'Tillicum', 'Canada', 'approved'),
  ('Happy Valley Peptides', 'Happy Valley Peptides', 'happyvalleypeptides.ca', 'https://happyvalleypeptides.ca', 'Happy Valley', 'Canada', 'approved'),
  ('Peachland Peptides', 'Peachland Peptides', 'peachlandpeptides.ca', 'https://peachlandpeptides.ca', 'Peachland', 'Canada', 'approved'),
  ('South Pandosy Peptides', 'South Pandosy Peptides', 'southpandosypeptides.ca', 'https://southpandosypeptides.ca', 'South Pandosy', 'Canada', 'approved'),
  ('Upper Mission Peptides', 'Upper Mission Peptides', 'uppermissionpeptides.ca', 'https://uppermissionpeptides.ca', 'Upper Mission', 'Canada', 'approved'),
  ('Kettle Valley Peptides', 'Kettle Valley Peptides', 'kettlevalleypeptides.ca', 'https://kettlevalleypeptides.ca', 'Kettle Valley', 'Canada', 'approved'),
  ('Winfield Peptides', 'Winfield Peptides', 'winfieldpeptides.ca', 'https://winfieldpeptides.ca', 'Winfield', 'Canada', 'approved'),
  ('Ellison Peptides', 'Ellison Peptides', 'ellisonpeptides.ca', 'https://ellisonpeptides.ca', 'Ellison', 'Canada', 'approved'),
  ('Black Mountain Peptides', 'Black Mountain Peptides', 'blackmountainpeptides.ca', 'https://blackmountainpeptides.ca', 'Black Mountain', 'Canada', 'approved'),
  ('Torbay Peptides', 'Torbay Peptides', 'torbaypeptides.ca', 'https://torbaypeptides.ca', 'Torbay', 'Canada', 'approved'),
  ('Portugal Cove-St. Philip''s Peptides', 'Portugal Cove-St. Philip''s Peptides', 'portugalcovestphilipspeptides.ca', 'https://portugalcovestphilipspeptides.ca', 'Portugal Cove-St. Philip''s', 'Canada', 'approved'),
  ('Chelmsford Peptides', 'Chelmsford Peptides', 'chelmsfordpeptides.ca', 'https://chelmsfordpeptides.ca', 'Chelmsford', 'Canada', 'approved'),
  ('Kenmount Terrace Peptides', 'Kenmount Terrace Peptides', 'kenmountterracepeptides.ca', 'https://kenmountterracepeptides.ca', 'Kenmount Terrace', 'Canada', 'approved'),
  ('Galway Peptides', 'Galway Peptides', 'galwaypeptides.ca', 'https://galwaypeptides.ca', 'Galway', 'Canada', 'approved'),
  ('Riverside Peptides', 'Riverside Peptides', 'riversidepeptides.ca', 'https://riversidepeptides.ca', 'Riverside', 'Canada', 'approved'),
  ('South Walkerville Peptides', 'South Walkerville Peptides', 'southwalkervillepeptides.ca', 'https://southwalkervillepeptides.ca', 'South Walkerville', 'Canada', 'approved'),
  ('Sandwich Peptides', 'Sandwich Peptides', 'sandwichpeptides.ca', 'https://sandwichpeptides.ca', 'Sandwich', 'Canada', 'approved'),
  ('Fonthill Peptides', 'Fonthill Peptides', 'fonthillpeptides.ca', 'https://fonthillpeptides.ca', 'Fonthill', 'Canada', 'approved'),
  ('Memramcook Peptides', 'Memramcook Peptides', 'memramcookpeptides.ca', 'https://memramcookpeptides.ca', 'Memramcook', 'Canada', 'approved'),
  ('Nicolet Peptides', 'Nicolet Peptides', 'nicoletpeptides.ca', 'https://nicoletpeptides.ca', 'Nicolet', 'Canada', 'approved'),
  ('Louiseville Peptides', 'Louiseville Peptides', 'louisevillepeptides.ca', 'https://louisevillepeptides.ca', 'Louiseville', 'Canada', 'approved'),
  ('Gananoque Peptides', 'Gananoque Peptides', 'gananoquepeptides.ca', 'https://gananoquepeptides.ca', 'Gananoque', 'Canada', 'approved'),
  ('Napanee Peptides', 'Napanee Peptides', 'napaneepeptides.ca', 'https://napaneepeptides.ca', 'Napanee', 'Canada', 'approved'),
  ('Collins Bay Peptides', 'Collins Bay Peptides', 'collinsbaypeptides.ca', 'https://collinsbaypeptides.ca', 'Collins Bay', 'Canada', 'approved'),
  ('Williamsville Peptides', 'Williamsville Peptides', 'williamsvillepeptides.ca', 'https://williamsvillepeptides.ca', 'Williamsville', 'Canada', 'approved'),
  ('Elora Peptides', 'Elora Peptides', 'elorapeptides.ca', 'https://elorapeptides.ca', 'Elora', 'Canada', 'approved'),
  ('The Ward Peptides', 'The Ward Peptides', 'thewardpeptides.ca', 'https://thewardpeptides.ca', 'The Ward', 'Canada', 'approved'),
  ('University District Peptides', 'University District Peptides', 'universitydistrictpeptides.ca', 'https://universitydistrictpeptides.ca', 'University District', 'Canada', 'approved'),
  ('Oliver Paipoonge Peptides', 'Oliver Paipoonge Peptides', 'oliverpaipoongepeptides.ca', 'https://oliverpaipoongepeptides.ca', 'Oliver Paipoonge', 'Canada', 'approved'),
  ('Intercity Peptides', 'Intercity Peptides', 'intercitypeptides.ca', 'https://intercitypeptides.ca', 'Intercity', 'Canada', 'approved'),
  ('Current River Peptides', 'Current River Peptides', 'currentriverpeptides.ca', 'https://currentriverpeptides.ca', 'Current River', 'Canada', 'approved'),
  ('Westfort Peptides', 'Westfort Peptides', 'westfortpeptides.ca', 'https://westfortpeptides.ca', 'Westfort', 'Canada', 'approved'),
  ('Innisfail Peptides', 'Innisfail Peptides', 'innisfailpeptides.ca', 'https://innisfailpeptides.ca', 'Innisfail', 'Canada', 'approved'),
  ('Bower Peptides', 'Bower Peptides', 'bowerpeptides.ca', 'https://bowerpeptides.ca', 'Bower', 'Canada', 'approved'),
  ('Timberlands Peptides', 'Timberlands Peptides', 'timberlandspeptides.ca', 'https://timberlandspeptides.ca', 'Timberlands', 'Canada', 'approved'),
  ('Taber Peptides', 'Taber Peptides', 'taberpeptides.ca', 'https://taberpeptides.ca', 'Taber', 'Canada', 'approved'),
  ('Westsyde Peptides', 'Westsyde Peptides', 'westsydepeptides.ca', 'https://westsydepeptides.ca', 'Westsyde', 'Canada', 'approved'),
  ('Dundas Peptides', 'Dundas Peptides', 'dundaspeptides.ca', 'https://dundaspeptides.ca', 'Dundas', 'Canada', 'approved'),
  ('High River Peptides', 'High River Peptides', 'highriverpeptides.ca', 'https://highriverpeptides.ca', 'High River', 'Canada', 'approved'),
  ('White Rock Peptides', 'White Rock Peptides', 'whiterockpeptides.ca', 'https://whiterockpeptides.ca', 'White Rock', 'Canada', 'approved'),
  ('Cataraqui Peptides', 'Cataraqui Peptides', 'cataraquipeptides.ca', 'https://cataraquipeptides.ca', 'Cataraqui', 'Canada', 'approved'),
  ('Valleyview Peptides', 'Valleyview Peptides', 'valleyviewpeptides.ca', 'https://valleyviewpeptides.ca', 'Valleyview', 'Canada', 'approved'),
  ('American Research Lab', 'American Research Lab', 'floridapeptideslab.com', 'https://floridapeptideslab.com', 'Florida', 'United States', 'approved'),
  ('Montreal Peptides Canada', 'Montreal Peptides Canada', 'montrealpeptides.ca', 'https://montrealpeptides.ca', 'Montreal', 'Canada', 'approved')
ON CONFLICT (domain) DO UPDATE SET
  legal_name=EXCLUDED.legal_name, trade_name=EXCLUDED.trade_name,
  website_url=EXCLUDED.website_url, city=EXCLUDED.city, country=EXCLUDED.country, updated_at=now();

-- Stores with NO domain — blank domain, inserted once (keyed on trade_name; skip nothing).
INSERT INTO vendor_profiles (legal_name, trade_name, city, country, status)
SELECT v.name, v.name, v.city, v.country, 'approved'
FROM (VALUES
  ('Orlando Peptides', 'Orlando', 'United States'),
  ('Main Street Peptides', 'Main Street', 'Canada'),
  ('Whyte Avenue Peptides', 'Whyte Avenue', 'Canada'),
  ('Summerland Peptides', 'Summerland', 'Canada'),
  ('Penticton Peptides', 'Penticton', 'Canada'),
  ('Vernon Peptides', 'Vernon', 'Canada'),
  ('Glenmore Peptides', 'Glenmore', 'Canada'),
  ('Gordon Head Peptides', 'Gordon Head', 'Canada'),
  ('Conception Bay South Peptides', 'Conception Bay South', 'Canada'),
  ('Sooke Peptides', 'Sooke', 'Canada'),
  ('Saint-Romuald Peptides', 'Saint-Romuald', 'Canada'),
  ('Laval-des-Rapides Peptides', 'Laval-des-Rapides', 'Canada'),
  ('Welland Peptides', 'Welland', 'Canada'),
  ('North Shore Peptides', 'North Shore', 'Canada'),
  ('Onaping Falls Peptides', 'Onaping Falls', 'Canada'),
  ('Hammond Bay Peptides', 'Hammond Bay', 'Canada'),
  ('Port Alberni Peptides', 'Port Alberni', 'Canada'),
  ('Smith-Ennismore-Lakefield Peptides', 'Smith-Ennismore-Lakefield', 'Canada'),
  ('Simcoe Peptides', 'Simcoe', 'Canada'),
  ('West Lincoln Peptides', 'West Lincoln', 'Canada'),
  ('Whitney Pier Peptides', 'Whitney Pier', 'Canada'),
  ('North Perth Peptides', 'North Perth', 'Canada'),
  ('Amos Peptides', 'Amos', 'Canada'),
  ('South Huron Peptides', 'South Huron', 'Canada'),
  ('Saint-Felicien Peptides', 'Saint-Felicien', 'Canada'),
  ('Cavan Monaghan Peptides', 'Cavan Monaghan', 'Canada'),
  ('Roberval Peptides', 'Roberval', 'Canada'),
  ('Mono Peptides', 'Mono', 'Canada'),
  ('HInton Peptides', 'HInton', 'Canada'),
  ('Marieville Peptides', 'Marieville', 'Canada'),
  ('Langdon Peptides', 'Langdon', 'Canada'),
  ('Stonewall Peptides', 'Stonewall', 'Canada'),
  ('Locke Street Peptides', 'Locke Street', 'Canada'),
  ('Timberlea Peptides', 'Timberlea', 'Canada'),
  ('Crystal Beach Peptides', 'Crystal Beach', 'Canada'),
  ('Midhurst Peptides', 'Midhurst', 'Canada'),
  ('Magnetic Hill Peptides', 'Magnetic Hill', 'Canada'),
  ('Mountain Road Peptides', 'Mountain Road', 'Canada'),
  ('Lewisville Peptides', 'Lewisville', 'Canada'),
  ('Lennoxville Peptides', 'Lennoxville', 'Canada'),
  ('Deauville Peptides', 'Deauville', 'Canada'),
  ('Bromptonville Peptides', 'Bromptonville', 'Canada'),
  ('Sainte-Marthe-du-Cap Peptides', 'Sainte-Marthe-du-Cap', 'Canada'),
  ('Pointe-du-Lac Peptides', 'Pointe-du-Lac', 'Canada'),
  ('Cataraqui Peptides', 'Cataraqui', 'Canada'),
  ('Valleyview Peptides', 'Valleyview', 'Canada'),
  ('Sahali Peptides', 'Sahali', 'Canada'),
  ('Juniper Ridge Peptides', 'Juniper Ridge', 'Canada'),
  ('Barnhartvale Peptides', 'Barnhartvale', 'Canada'),
  ('New Waterford Peptides', 'New Waterford', 'Canada'),
  ('Qualicum Beach Peptides', 'Qualicum Beach', 'Canada'),
  ('Departure Bay Peptides', 'Departure Bay', 'Canada'),
  ('Chase River Peptides', 'Chase River', 'Canada'),
  ('Azilda Peptides', 'Azilda', 'Canada'),
  ('Flour Mill Peptides', 'Flour Mill', 'Canada'),
  ('Minnow Lake Peptides', 'Minnow Lake', 'Canada'),
  ('South End Peptides', 'South End', 'Canada'),
  ('East City Peptides', 'East City', 'Canada'),
  ('Jackson Park Peptides', 'Jackson Park', 'Canada'),
  ('Eagle Place Peptides', 'Eagle Place', 'Canada'),
  ('Aberdeen Peptides', 'Aberdeen', 'Canada'),
  ('North Sydney Peptides', 'North Sydney', 'Canada'),
  ('Sydney Mines Peptides', 'Sydney Mines', 'Canada')
) AS v(name, city, country)
WHERE NOT EXISTS (SELECT 1 FROM vendor_profiles vp WHERE lower(vp.trade_name) = lower(v.name));
